-- ALMACEN_DICONSA definition

-- Drop table

-- DROP TABLE ALMACEN_DICONSA;

CREATE TABLE ALMACEN_DICONSA ( CLAVE_ALMACEN NUMERIC(5,0) NOT NULL, DESCRIPCION VARCHAR(40), CONSTRAINT PK_ALMACEN_DICONSA PRIMARY KEY (CLAVE_ALMACEN));


-- AREA definition

-- Drop table

-- DROP TABLE AREA;

CREATE TABLE AREA ( CLAVE_AREA NUMERIC(5,0) NOT NULL, DESCRIPCION VARCHAR(40), CONSTRAINT INTEG_237 PRIMARY KEY (CLAVE_AREA));
CREATE UNIQUE INDEX RDB$PRIMARY1 ON AREA (CLAVE_AREA);


-- BITACORA definition

-- Drop table

-- DROP TABLE BITACORA;

CREATE TABLE BITACORA ( ID_CONEXION INTEGER, USUARIO VARCHAR(15), FECHA_HORA TIMESTAMP, PROCESO VARCHAR(200), NOMBRE_ARCHIVO VARCHAR(160), OBSERVACIONES BLOB SUB_TYPE TEXT);


-- BITACORA_SAFCO definition

-- Drop table

-- DROP TABLE BITACORA_SAFCO;

CREATE TABLE BITACORA_SAFCO ( FECHA_PROCESO TIMESTAMP, FECHA_INICIO DATE, FECHA_FINAL DATE, USUARIO VARCHAR(60), OBSERVACION VARCHAR(100));


-- CALENDARIO_DISTRIBUCION definition

-- Drop table

-- DROP TABLE CALENDARIO_DISTRIBUCION;

CREATE TABLE CALENDARIO_DISTRIBUCION ( ANIO_PERIODO NUMERIC(4,0) NOT NULL, MES_PERIODO NUMERIC(2,0) NOT NULL, DIAS_HABILES SMALLINT NOT NULL, DIAS_DISTRIBUCION SMALLINT NOT NULL, LITROS_AUTORIZADOS_OF_SUB INTEGER, LITROS_AUTORIZADOS_OF_FRI INTEGER, LITROS_PROG_ANUAL_SUB INTEGER, LITROS_PROG_ANUAL_FRI INTEGER, DIAS_HABILES_POLVO NUMERIC(2,0) NOT NULL, CONSTRAINT INTEG_238 PRIMARY KEY (MES_PERIODO,ANIO_PERIODO));
CREATE UNIQUE INDEX RDB$PRIMARY2 ON CALENDARIO_DISTRIBUCION (MES_PERIODO,ANIO_PERIODO);


-- CIERRE_MENSUAL definition

-- Drop table

-- DROP TABLE CIERRE_MENSUAL;

CREATE TABLE CIERRE_MENSUAL ( MES_PERIODO NUMERIC(2,0), ANIO_PERIODO NUMERIC(4,0), CVE_PRODUCTO VARCHAR(11), FECHA_HORA_APLICACION TIMESTAMP, USUARIO_EJECUTOR VARCHAR(20), OBSERVACION BLOB SUB_TYPE TEXT, FECHA_CIERRE_PROGRAMADO DATE, CIERRE_DEFINITIVO NUMERIC(1,0), TIPO_PRODUCTO INTEGER, TIPO_PUNTO_VENTA INTEGER);


-- CLASIFICACION definition

-- Drop table

-- DROP TABLE CLASIFICACION;

CREATE TABLE CLASIFICACION ( CLAVE_CLASIFICACION NUMERIC(3,0) NOT NULL, DESCRIPCION VARCHAR(60), CONSTRAINT PK_CLASIFICACION PRIMARY KEY (CLAVE_CLASIFICACION));


-- CLASIFICACION_EMPRESA definition

-- Drop table

-- DROP TABLE CLASIFICACION_EMPRESA;

CREATE TABLE CLASIFICACION_EMPRESA ( ID_CLASIFICACION NUMERIC(5,0) NOT NULL, DESCRIPCION VARCHAR(60), CONSTRAINT PK_CLASIFICACION_EMPRESA PRIMARY KEY (ID_CLASIFICACION));


-- COMPANIA_TRANSPORTE definition

-- Drop table

-- DROP TABLE COMPANIA_TRANSPORTE;

CREATE TABLE COMPANIA_TRANSPORTE ( CLAVE_CIA NUMERIC(5,0) NOT NULL, DESCRIPCION VARCHAR(50), CONSTRAINT INTEG_240 PRIMARY KEY (CLAVE_CIA));
CREATE UNIQUE INDEX RDB$PRIMARY4 ON COMPANIA_TRANSPORTE (CLAVE_CIA);


-- CONC_PRUEBAS definition

-- Drop table

-- DROP TABLE CONC_PRUEBAS;

CREATE TABLE CONC_PRUEBAS ( FOLIO NUMERIC(10,0), CLAVE_CONC NUMERIC(6,0), LECHER NUMERIC(10,0), FECHA_INICIO DATE, FECHA_FIN DATE);


-- CONCESIONARIO definition

-- Drop table

-- DROP TABLE CONCESIONARIO;

CREATE TABLE CONCESIONARIO ( CLAVE_CONCESIONARIO NUMERIC(6,0) NOT NULL, NOMBRE VARCHAR(60), TELEFONO_CONCESIONARIO VARCHAR(20), CONSTRAINT INTEG_242 PRIMARY KEY (CLAVE_CONCESIONARIO));
CREATE UNIQUE INDEX RDB$PRIMARY6 ON CONCESIONARIO (CLAVE_CONCESIONARIO);


-- CONTRATO definition

-- Drop table

-- DROP TABLE CONTRATO;

CREATE TABLE CONTRATO ( CLAVE_CONTRATO NUMERIC(1,0) NOT NULL, DESCRIPCION VARCHAR(60), CONSTRAINT INTEG_243 PRIMARY KEY (CLAVE_CONTRATO));
CREATE UNIQUE INDEX RDB$PRIMARY7 ON CONTRATO (CLAVE_CONTRATO);


-- CONTROL_FOLIO_IMPRESOS definition

-- Drop table

-- DROP TABLE CONTROL_FOLIO_IMPRESOS;

CREATE TABLE CONTROL_FOLIO_IMPRESOS ( FOLIO_INICIAL_IMPRESO NUMERIC(10,0), FOLIO_FINAL_IMPRESO NUMERIC(10,0), FECHA_IMPRESION DATE, USUARIO_IMPRESOR CHAR(20));


-- DIAS_NO_VENTA_DETALLE definition

-- Drop table

-- DROP TABLE DIAS_NO_VENTA_DETALLE;

CREATE TABLE DIAS_NO_VENTA_DETALLE ( LECHER NUMERIC(10,0) NOT NULL, CVE_PRODUCTO VARCHAR(11) NOT NULL, FECHA_VENTA DATE NOT NULL, DOTACION_PROGRAMADA NUMERIC(5,0), FECHA_DISTRIBUCION DATE NOT NULL, CLAVE_RUTA NUMERIC(4,0), USUARIO_ACTUALIZADOR VARCHAR(15), USUARIO_REGISTRADOR VARCHAR(15), COMENTARIO_DAS30 BLOB SUB_TYPE TEXT, FOLIO_IMPRESO NUMERIC(10,0), CLAVE_PLANTA NUMERIC(5,0), CLAVE_RUTA_REPARTIDOR NUMERIC(5,0), SECUENCIA_DISTRIBUCION NUMERIC(5,0));


-- ENTIDAD definition

-- Drop table

-- DROP TABLE ENTIDAD;

CREATE TABLE ENTIDAD ( EFD_DESCRIPCION VARCHAR(60), EFD_NUMERO NUMERIC(2,0) NOT NULL, EFD_CORTO VARCHAR(2), CONSTRAINT INTEG_247 PRIMARY KEY (EFD_NUMERO));
CREATE UNIQUE INDEX RDB$PRIMARY11 ON ENTIDAD (EFD_NUMERO);


-- ESTADISTICA_FACTOR_RETIRO definition

-- Drop table

-- DROP TABLE ESTADISTICA_FACTOR_RETIRO;

CREATE TABLE ESTADISTICA_FACTOR_RETIRO ( LECHER NUMERIC(10,0), ANIO NUMERIC(4,0), ENE NUMERIC(3,3), FEB NUMERIC(3,3), MZO NUMERIC(3,3), ABR NUMERIC(3,3), MYO NUMERIC(3,3), JUN NUMERIC(3,3), JUL NUMERIC(3,3), AGO NUMERIC(3,3), SEP NUMERIC(3,3), OCT NUMERIC(3,3), NOV NUMERIC(3,3), DIC NUMERIC(3,3), FACTOR_RETIRO_PROMEDIO NUMERIC(3,3));


-- ESTADISTICA_INCIDENCIA_SEMANAL definition

-- Drop table

-- DROP TABLE ESTADISTICA_INCIDENCIA_SEMANAL;

CREATE TABLE ESTADISTICA_INCIDENCIA_SEMANAL ( LECHERIA NUMERIC(10,0), RUTA_DISTRIBUCION NUMERIC(5,0), MES_PERIODO NUMERIC(2,0), ANIO_PERIODO NUMERIC(4,0), LUNES INTEGER, MARTES INTEGER, MIERCOLES INTEGER, JUEVES INTEGER, VIERNES INTEGER, SABADO INTEGER, HORA_FECHA_GENERADO TIMESTAMP, CVE_PRODUCTO VARCHAR(11), TIPO_INCIDENCIA VARCHAR(20));


-- ESTADISTICA_INCIDENCIA_SEMANAL2 definition

-- Drop table

-- DROP TABLE ESTADISTICA_INCIDENCIA_SEMANAL2;

CREATE TABLE ESTADISTICA_INCIDENCIA_SEMANAL2 ( LECHERIA NUMERIC(10,0), RUTA_DISTRIBUCION NUMERIC(5,0), MES_PERIODO NUMERIC(2,0), ANIO_PERIODO NUMERIC(4,0), DOTACION_DISTRIBUIDA NUMERIC(8,0), LUNES_RTS INTEGER, MARTES_RTS INTEGER, MIERCOLES_RTS INTEGER, JUEVES_RTS INTEGER, VIERNES_RTS INTEGER, SABADO_RTS INTEGER, LUNES_FAL INTEGER, MARTES_FAL INTEGER, MIERCOLES_FAL INTEGER, JUEVES_FAL INTEGER, VIERNES_FAL INTEGER, SABADO_FAL INTEGER, LUNES_SOB INTEGER, MARTES_SOB INTEGER, MIERCOLES_SOB INTEGER, JUEVES_SOB INTEGER, VIERNES_SOB INTEGER, SABADO_SOB INTEGER, HORA_FECHA_GENERADO TIMESTAMP, CVE_PRODUCTO VARCHAR(11), TIPO_INCIDENCIA VARCHAR(20), DOMINGO_RTS INTEGER, DOMINGO_FAL INTEGER, DOMINGO_SOB INTEGER);


-- ESTADISTICA_ROTOS definition

-- Drop table

-- DROP TABLE ESTADISTICA_ROTOS;

CREATE TABLE ESTADISTICA_ROTOS ( CLAVE INTEGER, DESCRIPCION VARCHAR(60), ANIO_PERIODO NUMERIC(4,0), ENE_RT INTEGER, FEB_RT INTEGER, MZO_RT INTEGER, ABR_RT INTEGER, MYO_RT INTEGER, JUN_RT INTEGER, JUL_RT INTEGER, AGO_RT INTEGER, SEP_RT INTEGER, OCT_RT INTEGER, NOV_RT INTEGER, DIC_RT INTEGER, ENE_VT INTEGER, FEB_VT INTEGER, MZO_VT INTEGER, ABR_VT INTEGER, MYO_VT INTEGER, JUN_VT INTEGER, JUL_VT INTEGER, AGO_VT INTEGER, SEP_VT INTEGER, OCT_VT INTEGER, NOV_VT INTEGER, DIC_VT INTEGER, CVE_ENT NUMERIC(2,0), CVE_MUN NUMERIC(3,0), CVE_LOC NUMERIC(4,0));


-- ESTATUS_CAPTURA definition

-- Drop table

-- DROP TABLE ESTATUS_CAPTURA;

CREATE TABLE ESTATUS_CAPTURA ( CLAVE_ESTATUS_CAPTURA INTEGER, DESCRIPCION_ESTATUS VARCHAR(30));


-- ESTATUS_PEDIDO definition

-- Drop table

-- DROP TABLE ESTATUS_PEDIDO;

CREATE TABLE ESTATUS_PEDIDO ( CVE_ESTATUS NUMERIC(3,0) NOT NULL, DESCRIPCION VARCHAR(40), CONSTRAINT PK_ESTATUS_PEDIDO PRIMARY KEY (CVE_ESTATUS));


-- FOL_ACTA_DESTRUCCION definition

-- Drop table

-- DROP TABLE FOL_ACTA_DESTRUCCION;

CREATE TABLE FOL_ACTA_DESTRUCCION ( AD_HORA_FECHA_GENERACION TIMESTAMP, AD_PRONOMBRE CHAR(2), AD_NOMBRE_GERENTE CHAR(60), AD_PUESTO_GERENTE CHAR(60), AD_SUBGTE_ADMON CHAR(60), AD_SUBGTE_ADMON_PUESTO CHAR(60), AD_SUBGTE_PADRON CHAR(60), AD_SUBGTE_PADRON_PUESTO CHAR(60), AD_NOMBRE_RESPONSABLE CHAR(60), AD_PUESTO_RESPONSABLE CHAR(60), AD_OFICIO_REFERENCIA CHAR(40), AD_OFICIO_FECHA DATE, AD_OFICIO_TOTAL_TARJETAS NUMERIC(8,0), AD_OFICIO_FOLIO_INICIAL NUMERIC(15,0), AD_OFICIO_FOLIO_FINAL NUMERIC(15,0), AD_FECHA_MINIMA_ENTREGA_FOL DATE, AD_FECHA_MAXIMA_ENTREGA_FOL DATE, AD_TOTAL_TARJETAS NUMERIC(8,0), AD_ESTATUS_FOLIO NUMERIC(5,0));


-- FOL_ESTATUS definition

-- Drop table

-- DROP TABLE FOL_ESTATUS;

CREATE TABLE FOL_ESTATUS ( ESTATUS_FOLIO_CLAVE NUMERIC(5,0) NOT NULL, ESTATUS_FOLIO_DESCRIPCION CHAR(50), ESTATUS_FOLIO_CONTABILIZAR CHAR(1), CONSTRAINT PK_FOL_ESTUS PRIMARY KEY (ESTATUS_FOLIO_CLAVE));


-- FOL_OFICIO_RECEPCION definition

-- Drop table

-- DROP TABLE FOL_OFICIO_RECEPCION;

CREATE TABLE FOL_OFICIO_RECEPCION ( OFICIO_REFERENCIA CHAR(30) NOT NULL, OFICIO_FECHA DATE, OFICIO_FECHA_REGISTRO DATE, OFICIO_FOLIO_INICIAL NUMERIC(11,0), OFICIO_FOLIO_FINAL NUMERIC(11,0), OFICIO_CANTIDAD_RECIBIDA NUMERIC(10,0), OFICIO_REMESA_CERRADA VARCHAR(1), CONSTRAINT INTEG_249 PRIMARY KEY (OFICIO_REFERENCIA));
CREATE UNIQUE INDEX RDB$PRIMARY13 ON FOL_OFICIO_RECEPCION (OFICIO_REFERENCIA);


-- FOL_TIPO_FOLIO definition

-- Drop table

-- DROP TABLE FOL_TIPO_FOLIO;

CREATE TABLE FOL_TIPO_FOLIO ( TIPO_FOLIO_CLAVE NUMERIC(5,0) NOT NULL, TIPO_FOLIO_DESCRIPCION CHAR(50), CONSTRAINT PK_FOL_TIPO_FOLIO PRIMARY KEY (TIPO_FOLIO_CLAVE));


-- GRAFICA_COMPORTAMIENTO_PAS definition

-- Drop table

-- DROP TABLE GRAFICA_COMPORTAMIENTO_PAS;

CREATE TABLE GRAFICA_COMPORTAMIENTO_PAS ( CLAVE_CLASIF NUMERIC(2,0), CLAVE_RUBRO NUMERIC(2,0), ANIO_PERIODO NUMERIC(4,0), MES_PERIODO NUMERIC(2,0), CANTIDAD_PROG_ANUAL NUMERIC(15,3), CANTIDAD_PAS NUMERIC(15,3), MES_NOMBRE VARCHAR(5));


-- GRAFICA_COMPORTAMIENTO_PAS_IMP definition

-- Drop table

-- DROP TABLE GRAFICA_COMPORTAMIENTO_PAS_IMP;

CREATE TABLE GRAFICA_COMPORTAMIENTO_PAS_IMP ( CLAVE_CLASIF NUMERIC(2,0), CLAVE_RUBRO NUMERIC(2,0), ANIO_PERIODO NUMERIC(4,0), MES_1 NUMERIC(15,3), MES_2 NUMERIC(15,3), MES_3 NUMERIC(15,3), MES_4 NUMERIC(15,3), MES_5 NUMERIC(15,3), MES_6 NUMERIC(15,3), MES_7 NUMERIC(15,3), MES_8 NUMERIC(15,3), MES_9 NUMERIC(15,3), MES_10 NUMERIC(15,3), MES_11 NUMERIC(15,3), MES_12 NUMERIC(15,3), NOMBRE_SERIE VARCHAR(30));


-- GUIA_VENTA_2008_2013 definition

-- Drop table

-- DROP TABLE GUIA_VENTA_2008_2013;

CREATE TABLE GUIA_VENTA_2008_2013 ( LECHER NUMERIC(10,0) NOT NULL, CVE_PRODUCTO VARCHAR(11) NOT NULL, FECHA_VENTA DATE NOT NULL, DOTACION_PROGRAMADA NUMERIC(5,0), FECHA_DISTRIBUCION DATE NOT NULL, ROTOS NUMERIC(5,0), FALTANTES NUMERIC(5,0), SOBRANTES NUMERIC(5,0), TRASPASOS NUMERIC(5,0), DEGUSTACION NUMERIC(5,0), DEVOLUCION_PLANTA NUMERIC(5,0), COSTO_LITRO NUMERIC(8,2), OBSERVACIONES BLOB SUB_TYPE TEXT, CAPTURADO VARCHAR(1), OBSERVACIONES_TRANSPORTISTA BLOB SUB_TYPE TEXT, MES_PERIODO_CIERRE NUMERIC(2,0), FECHA_REGISTRO_GUIA DATE, FECHA_REGISTRO_VENTA DATE, FECHA_ACTUALIZACION DATE, ANIO_PERIODO_CIERRE NUMERIC(4,0), CLAVE_RUTA NUMERIC(4,0), OBSERVACIONES_DISTRIBUCION BLOB SUB_TYPE TEXT, REGISTRO_PROCESADO_SAFCO NUMERIC(1,0), OBSERVACION_COMENTARIO VARCHAR(200), USUARIO_ACTUALIZADOR VARCHAR(15), USUARIO_REGISTRADOR VARCHAR(15), COMENTARIO_DAS30 BLOB SUB_TYPE TEXT, HORA_ENTREGA TIMESTAMP, ROTOS_RECOGIDOS NUMERIC(5,0), CANASTILLAS_RECOGIDAS NUMERIC(5,0), ARCHIVO_DAS30_IMPRESO VARCHAR(180), FOLIO_IMPRESO NUMERIC(10,0), CLAVE_PLANTA NUMERIC(5,0), CLAVE_RUTA_REPARTIDOR NUMERIC(5,0), CLAVE_CIA NUMERIC(5,0), SECUENCIA_DISTRIBUCION NUMERIC(2,0));


-- HABILITAR_DAS_30 definition

-- Drop table

-- DROP TABLE HABILITAR_DAS_30;

CREATE TABLE HABILITAR_DAS_30 ( FECHA_INICIAL DATE, FECHA_FINAL DATE, CVE_PRODUCTO VARCHAR(11), CANTIDAD NUMERIC(5,0), PROCESADO NUMERIC(2,0));


-- INASISTENCIA_PASE_LISTA definition

-- Drop table

-- DROP TABLE INASISTENCIA_PASE_LISTA;

CREATE TABLE INASISTENCIA_PASE_LISTA ( ANIO_APLICACION NUMERIC(4,0) NOT NULL, LECHER NUMERIC(10,0) NOT NULL, TARJETA NUMERIC(5,0) NOT NULL, CT_PMT NUMERIC(6,0), PMT_NUMERO NUMERIC(3,0), CENTRO_TRABAJO NUMERIC(2,0), NOMBRE_TITULAR VARCHAR(40), APELLIDO_PATERNO VARCHAR(40), APELLIDO_MATERNO VARCHAR(40), RFC VARCHAR(13), HOMONIMIA NUMERIC(5,0), CLAVE_DOTACION NUMERIC(2,0), HORARIO_TARJETA VARCHAR(5), FECHA_HORA_SABE TIMESTAMP, FECHA_HORA_INICIO TIMESTAMP, FECHA_HORA_FINAL TIMESTAMP, FECHA_HORA_REGISTRO TIMESTAMP, FECHA_VIGENCIA DATE, ESTATUS_ASISTENCIA NUMERIC(1,0), CONSTRAINT PK_INASISTENCIA_PASE_LISTA PRIMARY KEY (ANIO_APLICACION,LECHER,TARJETA));


-- INVENTARIO_LEP_SUBSIDIADA definition

-- Drop table

-- DROP TABLE INVENTARIO_LEP_SUBSIDIADA;

CREATE TABLE INVENTARIO_LEP_SUBSIDIADA ( LECHER NUMERIC(10,0) NOT NULL, MES_PERIODO NUMERIC(2,0) NOT NULL, ANIO_PERIODO NUMERIC(4,0) NOT NULL, FECHA_TOMA_INVENTARIO DATE, CVE_PRODUCTO VARCHAR(11), INVENTARIO_INICIAL NUMERIC(8,0), INVENTARIO_FINAL NUMERIC(8,0), VENTA_REAL NUMERIC(8,0), SURTIMIENTO NUMERIC(8,0), VENTA_LIBRO_RETIRO NUMERIC(8,0), OBSERVACION BLOB SUB_TYPE TEXT, FECHA_HORA_REGISTRO TIMESTAMP, FECHA_HORA_ACTUALIZACION TIMESTAMP, USUARIO_REGISTRADOR VARCHAR(10), USUARIO_ACTUALIZADOR VARCHAR(10), DOTACION_PROGRAMADA NUMERIC(8,0), FECHA_TERMINA_INVENTARIO DATE, FECHA_CALCULO_SURTIMIENTO DATE, LITROS_SURTIR NUMERIC(8,0), MES_CALCULADO NUMERIC(2,0), ANIO_CALCULADO NUMERIC(4,0), LTS_PENDIENTES_SURTIR NUMERIC(8,0), PROMEDIO_LTS_POR_DIA NUMERIC(5,3), DIAS_INVENTARIO NUMERIC(3,0), DIAS_SURTIMIENTO NUMERIC(2,0), DEVOLUCION NUMERIC(5,0), SOBRANTE NUMERIC(5,0), FALTANTE NUMERIC(5,0), VENTA_SUSPENDIDA VARCHAR(1), CONSTRAINT PK_INVENTARIO_LEP_SUBSIDIADA PRIMARY KEY (LECHER,MES_PERIODO,ANIO_PERIODO));


-- KARDEX definition

-- Drop table

-- DROP TABLE KARDEX;

CREATE TABLE KARDEX ( CVE_PRODUCTO VARCHAR(11) NOT NULL, CONSEC NUMERIC(15,0) NOT NULL, FECHA_FOLIO DATE, TIPO_MOVIMIENTO VARCHAR(1), FOLIO NUMERIC(10,0), CANTIDAD NUMERIC(5,0), EXISTENCIA NUMERIC(5,0), FECHA_HORA_APLICACION TIMESTAMP, CONSTRAINT PK_KARDEX PRIMARY KEY (CVE_PRODUCTO,CONSEC));


-- MATRIZ_DIA_INVENTARIO definition

-- Drop table

-- DROP TABLE MATRIZ_DIA_INVENTARIO;

CREATE TABLE MATRIZ_DIA_INVENTARIO ( MES_PERIODO NUMERIC(2,0) NOT NULL, ANIO_PERIODO NUMERIC(4,0) NOT NULL, LECHERIA NUMERIC(10,0) NOT NULL, FECHA_TOMA_INVENTARIO DATE, FECHA_LIMITE_INVENTARIO DATE, DIAS_VENTA NUMERIC(2,0), CONSTRAINT PK_MATRIZ_DIA_INVENTARIO PRIMARY KEY (MES_PERIODO,ANIO_PERIODO,LECHERIA));


-- MENU definition

-- Drop table

-- DROP TABLE MENU;

CREATE TABLE MENU ( ID_MENU NUMERIC(3,0) NOT NULL, MENU_DESCRIPCION VARCHAR(60), MENU_HABILITAR VARCHAR(1), CONSTRAINT PK_MENU PRIMARY KEY (ID_MENU));


-- MENU_OPC_CONFIG definition

-- Drop table

-- DROP TABLE MENU_OPC_CONFIG;

CREATE TABLE MENU_OPC_CONFIG ( MENU_TIPO_ID NUMERIC(2,0) NOT NULL, NODO_PADRE INTEGER NOT NULL, NIVEL INTEGER, NODO INTEGER NOT NULL, OPC_VISIBLE VARCHAR(5), OPC_DESCRIPCION VARCHAR(60), OPC_TAG INTEGER, OPC_ABSOLUTE_INDEX INTEGER);
CREATE INDEX TABLE_09_FKINDEX1 ON MENU_OPC_CONFIG (MENU_TIPO_ID);
CREATE INDEX TABLE_09_FKINDEX2 ON MENU_OPC_CONFIG (NODO_PADRE,NODO);


-- MENU_OPCION definition

-- Drop table

-- DROP TABLE MENU_OPCION;

CREATE TABLE MENU_OPCION ( ID_ITEM NUMERIC(3,0) NOT NULL, ITEM_DESCRIPCION VARCHAR(60), ITEM_SELECCIONADO VARCHAR(1), CONSTRAINT PK_MENU_OPCION PRIMARY KEY (ID_ITEM));


-- MENU_TIPO_NIVEL definition

-- Drop table

-- DROP TABLE MENU_TIPO_NIVEL;

CREATE TABLE MENU_TIPO_NIVEL ( ID_MENU NUMERIC(3,0) NOT NULL, MENU_DESCRIPCION VARCHAR(60), MENU_HABILITAR VARCHAR(1), CONSTRAINT PK_MENU_TIPO_NIVEL PRIMARY KEY (ID_MENU));


-- MOVTOS_MASIVOS_DOTAC definition

-- Drop table

-- DROP TABLE MOVTOS_MASIVOS_DOTAC;

CREATE TABLE MOVTOS_MASIVOS_DOTAC ( FECHA_DISTRIBUCION DATE, FECHA_VENTA DATE, LECHERIA NUMERIC(10,0), CVE_PRODUCTO VARCHAR(11), DOTACION_LTS_ACTUAL NUMERIC(5,0), DOTACION_CANASTILLAS_ACTUAL NUMERIC(5,0), PORCENTAJE NUMERIC(3,0), DOTACION_LTS_NUEVOS NUMERIC(5,0), DOTACION_CANASTILLAS_NUEVAS NUMERIC(5,0), CANASTILLAS_AFECTADAS NUMERIC(5,0));


-- PADRON definition

-- Drop table

-- DROP TABLE PADRON;

CREATE TABLE PADRON ( MES_PERIODO NUMERIC(2,0) NOT NULL, ANIO_PERIODO NUMERIC(4,0) NOT NULL, LECHER NUMERIC(10,0) NOT NULL, TARJETA NUMERIC(5,0) NOT NULL, NOMBRE_TITULAR VARCHAR(60), PATERNO_TITULAR VARCHAR(60), MATERNO_TITULAR VARCHAR(60), DIAS_ASIGNADOS VARCHAR(6), MENORES NUMERIC(1,0), FOLIO_PREIMPRESO VARCHAR(11), NUMERO NUMERIC(4,0), LUN NUMERIC(1,0), MAR NUMERIC(1,0), MIE NUMERIC(1,0), JUE NUMERIC(1,0), VIE NUMERIC(1,0), SAB NUMERIC(1,0), DOTACION_TEORICA NUMERIC(3,0), DOTACION_RETIRADA NUMERIC(3,0), CAPTURADO NUMERIC(1,0), VIGENTE NUMERIC(1,0), CONSTRAINT PK_PADRON PRIMARY KEY (MES_PERIODO,ANIO_PERIODO,LECHER,TARJETA));


-- PADRON_DIC_COPIA definition

-- Drop table

-- DROP TABLE PADRON_DIC_COPIA;

CREATE TABLE PADRON_DIC_COPIA ( MES_PERIODO NUMERIC(2,0) NOT NULL, ANIO_PERIODO NUMERIC(4,0) NOT NULL, LECHER NUMERIC(10,0) NOT NULL, TARJETA NUMERIC(5,0) NOT NULL, NOMBRE_TITULAR VARCHAR(60), PATERNO_TITULAR VARCHAR(60), MATERNO_TITULAR VARCHAR(60), DIAS_ASIGNADOS VARCHAR(6), MENORES NUMERIC(1,0), FOLIO_PREIMPRESO VARCHAR(11), NUMERO NUMERIC(3,0), LUN NUMERIC(1,0), MAR NUMERIC(1,0), MIE NUMERIC(1,0), JUE NUMERIC(1,0), VIE NUMERIC(1,0), SAB NUMERIC(1,0), DOTACION_TEORICA NUMERIC(3,0), DOTACION_RETIRADA NUMERIC(3,0), CAPTURADO NUMERIC(1,0), VIGENTE NUMERIC(1,0));


-- PAS definition

-- Drop table

-- DROP TABLE PAS;

CREATE TABLE PAS ( CVE_PAS NUMERIC(5,0) NOT NULL, DESCRIPCION VARCHAR(60), CALLE VARCHAR(60), NUMERO_EXTERIOR VARCHAR(15), COLONIA VARCHAR(60), CODIGO_POSTAL NUMERIC(5,0), REFERENCIA VARCHAR(60), RFC VARCHAR(12), CONSTRAINT INTEG_255 PRIMARY KEY (CVE_PAS));
CREATE UNIQUE INDEX RDB$PRIMARY19 ON PAS (CVE_PAS);


-- PBL_CAUSA definition

-- Drop table

-- DROP TABLE PBL_CAUSA;

CREATE TABLE PBL_CAUSA ( PBL_CAUSA_ID NUMERIC(5,0) NOT NULL, PBL_CAUSA_DESCRIP VARCHAR(60), CONSTRAINT PK_PBL_CAUSA PRIMARY KEY (PBL_CAUSA_ID));


-- PL_SEPT2021 definition

-- Drop table

-- DROP TABLE PL_SEPT2021;

CREATE TABLE PL_SEPT2021 ( LECHER NUMERIC(10,0), TARJETA NUMERIC(5,0), ACTIVADA VARCHAR(1));


-- PLANTA definition

-- Drop table

-- DROP TABLE PLANTA;

CREATE TABLE PLANTA ( DESCRIPCION VARCHAR(60), CLAVE_PLANTA NUMERIC(5,0) NOT NULL, CONSTRAINT INTEG_256 PRIMARY KEY (CLAVE_PLANTA));
CREATE UNIQUE INDEX RDB$PRIMARY20 ON PLANTA (CLAVE_PLANTA);


-- PRECIO_PRODUCTO_HIST definition

-- Drop table

-- DROP TABLE PRECIO_PRODUCTO_HIST;

CREATE TABLE PRECIO_PRODUCTO_HIST ( CONSEC NUMERIC(10,0) NOT NULL, CLAVE_CONTRATO NUMERIC(1,0) NOT NULL, CVE_PRODUCTO VARCHAR(11) NOT NULL, PRECIO_LITRO_PUBLICO NUMERIC(8,4), PRECIO_LITRO_CONCESIONARIO NUMERIC(8,4), PORCENTAJE_GANANCIA FLOAT, FECHA_VIGENCIA_INICIAL DATE, FECHA_VIGENCIA_FINAL DATE, FECHA_HORA_REGISTRO TIMESTAMP, FECHA_HORA_ACTUALIZACION TIMESTAMP, USUARIO_REGISTRADOR VARCHAR(20), USUARIO_ACTUALIZADOR VARCHAR(20), CVE_PROD_SAFCO VARCHAR(3), CONSTRAINT UNQ_PRECIO_PRODUCTO_HIST_CONSEC UNIQUE (CONSEC));


-- PRG_DISTR_ANUAL definition

-- Drop table

-- DROP TABLE PRG_DISTR_ANUAL;

CREATE TABLE PRG_DISTR_ANUAL ( OFICIO_REFERENCIA VARCHAR(20), CLAVE_CLASIFICACION NUMERIC(4,0), CLAVE_RUBRO NUMERIC(4,0), ANIO NUMERIC(4,0), ENE NUMERIC(18,3), FEB NUMERIC(18,3), MAR NUMERIC(18,3), ABR NUMERIC(18,3), MYO NUMERIC(18,3), JUN NUMERIC(18,3), JUL NUMERIC(18,3), AGO NUMERIC(18,3), SEP NUMERIC(18,3), OCT NUMERIC(18,3), NOV NUMERIC(18,3), DIC NUMERIC(18,3));


-- PROBLEMA definition

-- Drop table

-- DROP TABLE PROBLEMA;

CREATE TABLE PROBLEMA ( MES_PERIODO NUMERIC(2,0) NOT NULL, ANIO_PERIODO NUMERIC(4,0) NOT NULL, LECHERIA NUMERIC(10,0) NOT NULL, DESCRIPCION_PROBLEMA BLOB SUB_TYPE TEXT, ORIGEN_REPORTE NUMERIC(1,0), TIPO_PROBLEMA_1 NUMERIC(2,0), TIPO_PROBLEMA_2 NUMERIC(2,0), TIPO_PROBLEMA_3 NUMERIC(2,0), TIPO_PROBLEMA_4 NUMERIC(2,0), TIPO_PROBLEMA_5 NUMERIC(2,0), DIAS_DESABASTO NUMERIC(2,0), VENTA_INVENTARIO NUMERIC(7,0), VENTA_LIBRO_RETIRO NUMERIC(7,0), DIAS_CERRADO NUMERIC(2,0), FECHA_CIERRE DATE, MOTIVO_CIERRE BLOB SUB_TYPE TEXT, SITUACION_ACTUAL_OPER NUMERIC(2,0), FECHA_SUSPENSION DATE, PROPUESTA_BAJA VARCHAR(1), DESCRIPCION_SOLUCION BLOB SUB_TYPE TEXT, ALTERNATIVA_DEFINITIVA INTEGER, FECHA_BAJA_SICOPA DATE, FECHA_INICIO_OPERACIONES DATE, QUIEN_VENDE VARCHAR(60), PERIODICIDAD NUMERIC(3,0), ACCIONES BLOB SUB_TYPE TEXT, FECHA_SOLUCION DATE, FECHA_ACTUALIZACION_SICOPA DATE, FECHA_REGISTRO DATE, FECHA_ACTUALIZACION DATE, USUARIO_REGISTRADOR VARCHAR(20), USUARIO_ACTUALIZADOR VARCHAR(20), CLAVE_LOCAL NUMERIC(2,0), CLAVE_ESQUEMA_TEMPORAL NUMERIC(2,0), CONSTRAINT PK_PROBLEMA PRIMARY KEY (MES_PERIODO,ANIO_PERIODO,LECHERIA));


-- PRODUCTO definition

-- Drop table

-- DROP TABLE PRODUCTO;

CREATE TABLE PRODUCTO ( CVE_PRODUCTO VARCHAR(11) NOT NULL, DESCRIPCION VARCHAR(100), ENVASE VARCHAR(20), VOLUMEN NUMERIC(5,0), UNIDAD_MEDIDA VARCHAR(3), EMBALAJE VARCHAR(20), PIEZAS NUMERIC(5,0), FOTO BLOB SUB_TYPE BINARY, ACTIVAR_PRODUCTO NUMERIC(1,0), DISTRIBUIDO_POR NUMERIC(5,0), TIPO_PRODUCTO NUMERIC(1,0) NOT NULL, EQUIVALENTE_LITROS NUMERIC(3,3) NOT NULL, TIPO_LECHE NUMERIC(1,0) NOT NULL, CVE_PRODUCTO_SAFCO VARCHAR(3), COD_PRODUCTO_SAFCO VARCHAR(4), SKU NUMERIC(13,0), STOCK_MINIMO NUMERIC(5,0), STOCK_INICIAL NUMERIC(5,0), STOCK_ACTUAL NUMERIC(5,0), CONTROL_KARDEX VARCHAR(1), CONSTRAINT INTEG_258 PRIMARY KEY (CVE_PRODUCTO));
CREATE UNIQUE INDEX RDB$PRIMARY22 ON PRODUCTO (CVE_PRODUCTO);


-- PROMOTOR definition

-- Drop table

-- DROP TABLE PROMOTOR;

CREATE TABLE PROMOTOR ( PMT_NUMERO SMALLINT NOT NULL, PMT_NOMBRE VARCHAR(60), PMT_TELEFONO_CASA CHAR(30), PMT_TELEFONO_CELULAR CHAR(30), PMT_ACTIVO VARCHAR(1), CONSTRAINT PK_PROMOTOR PRIMARY KEY (PMT_NUMERO));


-- PRUEBA definition

-- Drop table

-- DROP TABLE PRUEBA;

CREATE TABLE PRUEBA ( ID_PBL NUMERIC(3,0));


-- PUESTO definition

-- Drop table

-- DROP TABLE PUESTO;

CREATE TABLE PUESTO ( DESCRIPCION VARCHAR(60), CLAVE_PUESTO NUMERIC(5,0) NOT NULL, CONSTRAINT INTEG_260 PRIMARY KEY (CLAVE_PUESTO));
CREATE UNIQUE INDEX RDB$PRIMARY24 ON PUESTO (CLAVE_PUESTO);


-- REPORTE_DESPACHO definition

-- Drop table

-- DROP TABLE REPORTE_DESPACHO;

CREATE TABLE REPORTE_DESPACHO ( LTS_SUBSIDIADA1 INTEGER, FECHA DATE, LTS_FRISIA1 INTEGER, LTS_SUBSIDIADA2 INTEGER, LTS_FRISIA2 INTEGER, CVE_PLANTA NUMERIC(5,0), LTS_AUTORIZADOS_SUB_OF INTEGER, LTS_AUTORIZADOS_FRI_OF INTEGER, PROG_ANUAL_SUB INTEGER, PROG_ANUAL_FRISIA INTEGER, CLAVE_ELABORO NUMERIC(5,0), CLAVE_VOBO NUMERIC(5,0));


-- REPORTE_DESPACHO1 definition

-- Drop table

-- DROP TABLE REPORTE_DESPACHO1;

CREATE TABLE REPORTE_DESPACHO1 ( PLANTA NUMERIC(3,0), PRODUCTO VARCHAR(11), FECHA_EMBARQUE DATE, LITROS NUMERIC(8,0));


-- REPORTE_DESPACHO_2 definition

-- Drop table

-- DROP TABLE REPORTE_DESPACHO_2;

CREATE TABLE REPORTE_DESPACHO_2 ( PRODUCTO VARCHAR(11), CLAVE_RUTA_REPARTIDOR NUMERIC(5,0), PLANTA NUMERIC(5,0), FECHA_EMBARQUE DATE, LITROS NUMERIC(9,0), OBSERVACIONES VARCHAR(200), LTS_AUT_SUB_OF INTEGER, LTS_AUT_FRI_OF INTEGER, PROG_ANUAL_SUB INTEGER, PROG_ANUAL_FRISIA INTEGER, CLAVE_ELABORO NUMERIC(5,0), CLAVE_VOBO NUMERIC(5,0));


-- REPORTE_FALTANTE definition

-- Drop table

-- DROP TABLE REPORTE_FALTANTE;

CREATE TABLE REPORTE_FALTANTE ( FECHA_VENTA DATE NOT NULL, LECHERIA NUMERIC(10,0) NOT NULL, PROCESADO_SAFCO NUMERIC(1,0), USUARIO_REGISTRADOR VARCHAR(15), FECHA_HORA_MOVIMIENTO TIMESTAMP, USUARIO_ACTUALIZADOR VARCHAR(15), FOLIO_IMPRESO NUMERIC(10,0));


-- REPORTE_GUIA_FRISIA definition

-- Drop table

-- DROP TABLE REPORTE_GUIA_FRISIA;

CREATE TABLE REPORTE_GUIA_FRISIA ( LECHER NUMERIC(10,0) NOT NULL, CANASTILLAS_LUNES NUMERIC(3,0), CANASTILLAS_MARTES NUMERIC(3,0), CANASTILLAS_MIERCOLES NUMERIC(3,0), CANASTILLAS_JUEVES NUMERIC(3,0), CANASTILLAS_VIERNES NUMERIC(3,0), CANASTILLAS_SABADO NUMERIC(3,0), DIA_1 NUMERIC(2,0), DIA_2 NUMERIC(2,0), DIA_3 NUMERIC(2,0), DIA_4 NUMERIC(2,0), DIA_5 NUMERIC(2,0), DIA_6 NUMERIC(2,0), CONSTRAINT PK_REPORTE_GUIA_FRISIA PRIMARY KEY (LECHER));


-- REQUERIMIENTO definition

-- Drop table

-- DROP TABLE REQUERIMIENTO;

CREATE TABLE REQUERIMIENTO ( ID_REQUERIMIENTO NUMERIC(5,0) NOT NULL, FECHA_HORA_REGISTRO TIMESTAMP, FECHA_REQUERIMIENTO DATE, FECHA_ENTRADA DATE, ESTATUS_REQUERIMIENTO NUMERIC(1,0), OBSERVACION VARCHAR(200), CONSTRAINT PK_REQUERIMIENTO PRIMARY KEY (ID_REQUERIMIENTO));


-- RESUMEN_EMBARQUE definition

-- Drop table

-- DROP TABLE RESUMEN_EMBARQUE;

CREATE TABLE RESUMEN_EMBARQUE ( LECHERIA NUMERIC(10,0) NOT NULL, CVE_PRODUCTO VARCHAR(11) NOT NULL, FECHA_EMBARQUE DATE NOT NULL, FECHA_VENTA DATE, DOTACION_PROGRAMADA NUMERIC(8,0), DEVUELTOS NUMERIC(8,0), ROTOS NUMERIC(8,0), FALTANTES NUMERIC(8,0), SOBRANTES NUMERIC(8,0), FECHA_EJECUCION DATE, CONSTRAINT PK_RESUMEN_EMBARQUE PRIMARY KEY (LECHERIA,CVE_PRODUCTO,FECHA_EMBARQUE));


-- RESUMEN_EMBARQUES_INCIDENCIAS definition

-- Drop table

-- DROP TABLE RESUMEN_EMBARQUES_INCIDENCIAS;

CREATE TABLE RESUMEN_EMBARQUES_INCIDENCIAS ( FECHA_EMBARQUE DATE, PLANTA CHAR(20), CVE_PRODUCTO VARCHAR(11), NOMB_PRODUCTO VARCHAR(30), LTS_EMBARCADOS NUMERIC(6,0), ROTOS NUMERIC(5,0), FALTANTES NUMERIC(5,0), SOBRANTES NUMERIC(5,0), DEVUELTOS NUMERIC(5,0));


-- RPT_PASO_E_S definition

-- Drop table

-- DROP TABLE RPT_PASO_E_S;

CREATE TABLE RPT_PASO_E_S ( MOVIMIENTO_E_S_1 VARCHAR(1), MOVIMIENTO_E_S_2 VARCHAR(1), FOLIO_1 NUMERIC(10,0), FOLIO_2 NUMERIC(10,0), FECHA_FOLIO_1 DATE, FECHA_FOLIO_2 DATE, NOMBRE_RECIBE_1 VARCHAR(60), NOMBRE_RECIBE_2 VARCHAR(60), RECIBI_DE_1 VARCHAR(60), RECIBI_DE_2 VARCHAR(60), ID_DOCUMENTO_1 VARCHAR(15), ID_DOCUMENTO_2 VARCHAR(15), ID_PEDIDO_1 NUMERIC(10,0), ID_PEDIDO_2 NUMERIC(10,0), NOMBRE_AUTORIZO_1 VARCHAR(60), NOMBRE_AUTORIZO_2 VARCHAR(60), NOMBRE_SOLICITA_1 VARCHAR(60), NOMBRE_SOLICITA_2 VARCHAR(60), NOMBRE_ENTREGADO_1 VARCHAR(60), NOMBRE_ENTREGADO_2 VARCHAR(60), ID_CONCEPTO_E_S_1 NUMERIC(3,0), ID_CONCEPTO_E_S_2 NUMERIC(3,0), OBSERVACIONES_1 BLOB SUB_TYPE TEXT, OBSERVACIONES_2 BLOB SUB_TYPE TEXT, DOCUMENTO_1 VARCHAR(25), DOCUMENTO_2 VARCHAR(25), AFECTADO_KARDEX_1 NUMERIC(1,0), AFECTADO_KARDEX_2 NUMERIC(1,0));


-- RPT_PASO_E_S_DETALLE definition

-- Drop table

-- DROP TABLE RPT_PASO_E_S_DETALLE;

CREATE TABLE RPT_PASO_E_S_DETALLE ( MOVIMIENTO_E_S_1 VARCHAR(1), FOLIO_1 NUMERIC(10,0), CONSEC_1 NUMERIC(5,0), CANTIDAD_SOLICITADA_1 NUMERIC(5,0), CANTIDAD_SURTIDA_1 NUMERIC(5,0), UNIDAD_PRODUCTO_1 VARCHAR(20), OBSERVACION_1 VARCHAR(60), DESCRIPCION VARCHAR(100), CODIFICACION NUMERIC(4,0));


-- RPT_REQ_DETALLE definition

-- Drop table

-- DROP TABLE RPT_REQ_DETALLE;

CREATE TABLE RPT_REQ_DETALLE ( CVE_PRODUCTO VARCHAR(11), CANTIDAD NUMERIC(5,0), CONSEC NUMERIC(5,0), ID_REQUERIMIENTO NUMERIC(5,0), DESCRIPCION VARCHAR(100), EMBALAJE VARCHAR(40));


-- RPT_RESUMEN definition

-- Drop table

-- DROP TABLE RPT_RESUMEN;

CREATE TABLE RPT_RESUMEN ( RPT_CONTRATO INTEGER, RPT_PRESENTACION INTEGER, RPT_DESCRIPCION VARCHAR(60), RPT_CANT_LECHERIAS INTEGER, RPT_FAMILIAS INTEGER, RPT_MENORES INTEGER, RPT_MAYORES INTEGER, RPT_TOT_PADRON INTEGER, RPT_VENTAS INTEGER, RPT_FACTOR_RETIRO FLOAT, RPT_MES_CIERRE NUMERIC(2,0), RPT_ANIO_CIERRE NUMERIC(4,0), RPT_TIPO_CIERRE INTEGER, RPT_DIAS_VENTA NUMERIC(2,0));


-- RUTA_LECHE_COMERCIAL definition

-- Drop table

-- DROP TABLE RUTA_LECHE_COMERCIAL;

CREATE TABLE RUTA_LECHE_COMERCIAL ( CLAVE_RUTA_LC NUMERIC(5,0) NOT NULL, DESCRIPCION VARCHAR(40), CONSTRAINT PK_RUTA_LECHE_COMERCIAL PRIMARY KEY (CLAVE_RUTA_LC));


-- RUTA_REPARTIDOR definition

-- Drop table

-- DROP TABLE RUTA_REPARTIDOR;

CREATE TABLE RUTA_REPARTIDOR ( DESCRIPCION VARCHAR(60), CLAVE_RUTA_REPARTIDOR INTEGER NOT NULL, CLAVE_PLANTA NUMERIC(5,0), CONSTRAINT INTEG_263 PRIMARY KEY (CLAVE_RUTA_REPARTIDOR));
CREATE UNIQUE INDEX RDB$PRIMARY27 ON RUTA_REPARTIDOR (CLAVE_RUTA_REPARTIDOR);


-- SEGURO_POPULAR definition

-- Drop table

-- DROP TABLE SEGURO_POPULAR;

CREATE TABLE SEGURO_POPULAR ( LECHERIA NUMERIC(10,0), TARJETA NUMERIC(5,0), CURP VARCHAR(18), RFC VARCHAR(13), NOMBRE_BENEFICIARIO VARCHAR(60), DESCRIPCION VARCHAR(200));


-- SF_CONCESIO_ANALISIS definition

-- Drop table

-- DROP TABLE SF_CONCESIO_ANALISIS;

CREATE TABLE SF_CONCESIO_ANALISIS ( CSNOMBRE VARCHAR(120), CSNUMERO VARCHAR(7), CSLECHER VARCHAR(10), CSLECH VARCHAR(10), CS_CONDIS VARCHAR(3), CSCONREF VARCHAR(1), CSPRODUC VARCHAR(12), CSEX VARCHAR(1), CSOTRO VARCHAR(1), CSFECOTRO DATE, CSDIAS VARCHAR(2), CSOBSERV VARCHAR(100), CSSECTOR VARCHAR(2), CS_EX VARCHAR(2));


-- SF_CONCESIONARIO definition

-- Drop table

-- DROP TABLE SF_CONCESIONARIO;

CREATE TABLE SF_CONCESIONARIO ( CSNOMBRE VARCHAR(120), CSNUMERO VARCHAR(7), CSLECHER VARCHAR(10), CSLECH VARCHAR(10), CS_CONDIS VARCHAR(3), CSCONREF VARCHAR(1), CSPRODUC VARCHAR(12), CSEX VARCHAR(1), CSOTRO VARCHAR(1), CSFECOTRO DATE, CSDIAS VARCHAR(2), CSOBSERV VARCHAR(100), CSSECTOR VARCHAR(2));


-- SF_DEPOSITO_ANALISIS definition

-- Drop table

-- DROP TABLE SF_DEPOSITO_ANALISIS;

CREATE TABLE SF_DEPOSITO_ANALISIS ( CONSECUTIVO NUMERIC(5,0), REFERENCIA VARCHAR(7), FORMA_PAGO VARCHAR(5), NOMBRE VARCHAR(20), SUCURSAL_BANCO VARCHAR(4), SIGNO_ARITMETICO CHAR(1), IMPORTE NUMERIC(15,2), CARACTER_DECIMAL CHAR(1), FECHA_DEPOSITO DATE, CUENTA_BANCO VARCHAR(10), NOMBRE_ARCHIVO VARCHAR(40), MES_PERIODO NUMERIC(2,0), ANIO_PERIODO NUMERIC(4,0));


-- SF_LECHERIA definition

-- Drop table

-- DROP TABLE SF_LECHERIA;

CREATE TABLE SF_LECHERIA ( LHNUMERO VARCHAR(10), LHREFER VARCHAR(7), LHCONTRAT VARCHAR(3), LHCALLEN VARCHAR(50), LHCOL VARCHAR(50), LHENTRE VARCHAR(50), LHDELMUN VARCHAR(25), LHCODP VARCHAR(5), LHTEL VARCHAR(20), LHFECAP DATE, LHTIPO VARCHAR(3), LHTLOCAL VARCHAR(2), LHTIPOLEC VARCHAR(3), LHDOTA_D NUMERIC(5,0), LHDIASEM VARCHAR(7), LHDOT001 NUMERIC(7,0), LHDIE001 VARCHAR(7), LHDOT003 NUMERIC(7,0), LHDIE003 VARCHAR(7), LHDISTAN NUMERIC(6,0), LHRURA_UR VARCHAR(1), LHBENEF_N NUMERIC(5,0), LHBENEF_A NUMERIC(5,0), LHREGION VARCHAR(2), LHRUTA VARCHAR(3), LHZONA VARCHAR(1), ES_FRISIA VARCHAR(1));


-- SF_LECHERIA_FRISIA definition

-- Drop table

-- DROP TABLE SF_LECHERIA_FRISIA;

CREATE TABLE SF_LECHERIA_FRISIA ( LECHERIA_SIDIST BIGINT NOT NULL, LECHERIA_SAFCO BIGINT, ES_FRISIA VARCHAR(1));


-- SF_PRODUCTO_ANALISIS definition

-- Drop table

-- DROP TABLE SF_PRODUCTO_ANALISIS;

CREATE TABLE SF_PRODUCTO_ANALISIS ( PROD_CLAVE NUMERIC(3,0), PROD_CONTRATO NUMERIC(2,0), PROD_PROGRA VARCHAR(50), PROD_DESCRIPCION VARCHAR(60), PROD_PRESENTACION VARCHAR(20), PROD_UNIDAD VARCHAR(20), PROD_MEDIDA VARCHAR(3), PROD_EQUIVA NUMERIC(10,4), PROD_ABREV VARCHAR(20));


-- SF_REPORTE_CONCILIACION definition

-- Drop table

-- DROP TABLE SF_REPORTE_CONCILIACION;

CREATE TABLE SF_REPORTE_CONCILIACION ( FECHA_VENTA DATE, LECHER NUMERIC(10,0), NOMBRE_LECHERIA VARCHAR(60), SID_DOTACION INTEGER, SID_ROTOS INTEGER, SID_FALTANTES INTEGER, SID_SOBRANTES INTEGER, SID_TRASPASO INTEGER, SID_DEGUSTACION INTEGER, SID_DEVOLUCION INTEGER, SAF_DOTACION INTEGER, SAF_ROTOS INTEGER, SAF_FALTANTES INTEGER, SAF_SOBRANTES INTEGER, CVE_PRODUCTO VARCHAR(11), MES_PERIODO SMALLINT, ANIO_PERIODO SMALLINT, DESCRIPCION_PRODUCTO VARCHAR(30));


-- SF_SALDO definition

-- Drop table

-- DROP TABLE SF_SALDO;

CREATE TABLE SF_SALDO ( CONCES VARCHAR(7) NOT NULL, NOMBRE VARCHAR(26), CVE_CLIENTE VARCHAR(10), ZONA VARCHAR(1), CON VARCHAR(3), ADEUDO NUMERIC(12,2), BRUTO NUMERIC(11,4), ROTO NUMERIC(6,2), FALTA NUMERIC(6,2), SOBRA NUMERIC(6,2), SURTIDO NUMERIC(11,4), CARGO NUMERIC(14,4), ABONO NUMERIC(14,4), SALDO NUMERIC(14,4), ATRASO NUMERIC(10,2), NOTA VARCHAR(6), ROT_FAL NUMERIC(6,0), REGION VARCHAR(2), RUTA VARCHAR(3));


-- SF_SALDO_ANALISIS definition

-- Drop table

-- DROP TABLE SF_SALDO_ANALISIS;

CREATE TABLE SF_SALDO_ANALISIS ( MES_PERIODO NUMERIC(2,0) NOT NULL, ANIO_PERIODO NUMERIC(4,0) NOT NULL, CONCES VARCHAR(7) NOT NULL, NOMBRE VARCHAR(26), CVE_CLIENTE VARCHAR(10), ZONA VARCHAR(1), CON VARCHAR(3), ADEUDO NUMERIC(12,2), BRUTO NUMERIC(11,4), ROTO NUMERIC(6,2), FALTA NUMERIC(6,2), SOBRA NUMERIC(6,2), SURTIDO NUMERIC(11,4), CARGO NUMERIC(14,4), ABONO NUMERIC(14,4), SALDO NUMERIC(14,4), REGION VARCHAR(2), RUTA VARCHAR(3), COMENTARIO VARCHAR(100), SALDO_MES_ANTERIOR NUMERIC(14,4), SALDO_POR_VENCER NUMERIC(14,4), SALDO_30_DIAS NUMERIC(14,4), SALDO_60_DIAS NUMERIC(14,4), SALDO_90_DIAS NUMERIC(14,4), SALDO_MAS_90 NUMERIC(14,4), SALDO_MAS_90_PERIODO VARCHAR(7), ML_TVENTA NUMERIC(1,0), CVE_RUTA_PROMOTOR NUMERIC(4,0), TIPO_CONTRATO NUMERIC(2,0), OBSERVACIONES BLOB SUB_TYPE TEXT);


-- SF_SALDO_PROCESADO definition

-- Drop table

-- DROP TABLE SF_SALDO_PROCESADO;

CREATE TABLE SF_SALDO_PROCESADO ( CONCES VARCHAR(7), NOMBRE VARCHAR(26), CVE_CLIENTE VARCHAR(10), SALDO NUMERIC(14,2), CS_CONDIS VARCHAR(3), CVE_RUTA_PMT NUMERIC(4,0), TIPO_CONTRATO NUMERIC(1,0), EXCONC VARCHAR(2), LITROS_SURTIDOS NUMERIC(8,0), PRECIO_LITRO NUMERIC(8,4), DEPOSITOS NUMERIC(14,2), FECHA_INICIO DATE, FECHA_FINAL DATE, CVE_PRODUCTO VARCHAR(11));


-- SF_SURTIDO definition

-- Drop table

-- DROP TABLE SF_SURTIDO;

CREATE TABLE SF_SURTIDO ( STFECHA DATE, STREGION VARCHAR(2), STCONCES VARCHAR(7), STRUTA VARCHAR(3), STPRODUCTO VARCHAR(3), STCODIGO VARCHAR(4), STLITROS NUMERIC(8,0), STROTOS NUMERIC(5,0), STFALTANTES NUMERIC(5,0), STSOBRA NUMERIC(5,0), STINVEN_L NUMERIC(8,0), STLECHER VARCHAR(10), STIMPORTE NUMERIC(10,2), STIMP_IVA NUMERIC(10,2), STCIERRE VARCHAR(6), STCONF_RF VARCHAR(1), STFACTURA VARCHAR(1), STNUMFACT VARCHAR(6));


-- STOCK definition

-- Drop table

-- DROP TABLE STOCK;

CREATE TABLE STOCK ( FOLIO_MOVIMIENTO NUMERIC(10,0) NOT NULL, FECHA_HORA_MOVIMIENTO TIMESTAMP, TIPO_MOVIMIENTO VARCHAR(1), CLAVE_TIPO_MOVIMIENTO NUMERIC(3,0), FOLIO_NOTA_VENTA NUMERIC(10,0), CODIGO_PRODUCTO VARCHAR(12), CANTIDAD NUMERIC(10,0), OBSERVACION VARCHAR(100), PROVEEDOR VARCHAR(60), COMPROBANTE VARCHAR(10), CONSTRAINT PK_STOCK PRIMARY KEY (FOLIO_MOVIMIENTO));


-- SUPERVISOR definition

-- Drop table

-- DROP TABLE SUPERVISOR;

CREATE TABLE SUPERVISOR ( ID_SUPERVISOR NUMERIC(5,0) NOT NULL, NOMBRE_SUPERVISOR VARCHAR(60), TELEFONO VARCHAR(40), CONSTRAINT PK_SUPERVISOR PRIMARY KEY (ID_SUPERVISOR));


-- SURTIMIENTO_POLVO definition

-- Drop table

-- DROP TABLE SURTIMIENTO_POLVO;

CREATE TABLE SURTIMIENTO_POLVO ( MES_PERIODO NUMERIC(2,0) NOT NULL, ANIO_PERIODO NUMERIC(4,0) NOT NULL, LECHER NUMERIC(10,0) NOT NULL, ID_FACTURA VARCHAR(15) NOT NULL, CVE_PRODUCTO VARCHAR(11) NOT NULL, FECHA_TOMA_INVENTARIO DATE, CAJAS NUMERIC(5,0), LITROS NUMERIC(8,0), FECHA_CADUCIDAD DATE, USUARIO_REGISTRADOR VARCHAR(40), USUARIO_ACTUALIZADOR VARCHAR(40), FECHA_FACTURA DATE, CONSTRAINT PK_SURTIMIENTO_POLVO PRIMARY KEY (MES_PERIODO,ANIO_PERIODO,LECHER,ID_FACTURA));


-- SUSPENSION definition

-- Drop table

-- DROP TABLE SUSPENSION;

CREATE TABLE SUSPENSION ( CLAVE_SUSPENSION SMALLINT NOT NULL, DESCRIPCION_SUSPENSION VARCHAR(60), CONSTRAINT PK_SUSPENSION PRIMARY KEY (CLAVE_SUSPENSION));


-- TARJETAS definition

-- Drop table

-- DROP TABLE TARJETAS;

CREATE TABLE TARJETAS ( LECHERIA NUMERIC(10,0), FOLIO NUMERIC(11,0), TARJETA NUMERIC(5,0), TITULAR CHAR(60), FECHA_IMPRESION DATE);


-- TARJETAS_RESUMEN definition

-- Drop table

-- DROP TABLE TARJETAS_RESUMEN;

CREATE TABLE TARJETAS_RESUMEN ( LECHERIA NUMERIC(10,0), FOLIO_INICIAL NUMERIC(11,0), FOLIO_FINAL NUMERIC(11,0), FECHA_IMPRESION DATE);


-- TIEMPO_RECORRIDO_DESCARGA definition

-- Drop table

-- DROP TABLE TIEMPO_RECORRIDO_DESCARGA;

CREATE TABLE TIEMPO_RECORRIDO_DESCARGA ( CLAVE_RUTA NUMERIC(5,0) NOT NULL, LECHERIA NUMERIC(10,0) NOT NULL, KMS FLOAT, TIEMPO_RECORRIDO TIMESTAMP, TIEMPO_DESCARGA TIMESTAMP, CLAVE_PLANTA SMALLINT);


-- TIEMPO_RECORRIDO_DESCARGA_HIST definition

-- Drop table

-- DROP TABLE TIEMPO_RECORRIDO_DESCARGA_HIST;

CREATE TABLE TIEMPO_RECORRIDO_DESCARGA_HIST ( LECHERIA NUMERIC(10,0) NOT NULL, MES_PERIODO NUMERIC(2,0) NOT NULL, ANIO_PERIODO NUMERIC(4,0) NOT NULL, CLAVE_RUTA NUMERIC(5,0) NOT NULL, PRIORIDAD SMALLINT, KMS FLOAT, DOTACION_MENSUAL INTEGER, DOTACION_MENSUAL_FRISIA INTEGER, CIERRE VARCHAR(1), TIEMPO_RECORRIDO TIMESTAMP, TIEMPO_DESCARGA TIMESTAMP, COMENTARIO VARCHAR(60), CLAVE_PLANTA NUMERIC(5,0), PERIODO_CERRADO CHAR(1));


-- TIPO_CAJA definition

-- Drop table

-- DROP TABLE TIPO_CAJA;

CREATE TABLE TIPO_CAJA ( CLAVE_CAJA SMALLINT NOT NULL, DESCRIPCION_CAJA VARCHAR(60), CONSTRAINT PK_TIPO_CAJA PRIMARY KEY (CLAVE_CAJA));


-- TIPO_CAMION definition

-- Drop table

-- DROP TABLE TIPO_CAMION;

CREATE TABLE TIPO_CAMION ( CLAVE_TIPO_CAMION SMALLINT NOT NULL, DESCRIPCION_CAMION VARCHAR(60), CONSTRAINT PK_TIPO_CAMION PRIMARY KEY (CLAVE_TIPO_CAMION));


-- TIPO_LOCAL definition

-- Drop table

-- DROP TABLE TIPO_LOCAL;

CREATE TABLE TIPO_LOCAL ( LOCAL_ID NUMERIC(2,0) NOT NULL, LOCAL_DESCRIPCION VARCHAR(60), CONSTRAINT PK_TIPO_LOCAL PRIMARY KEY (LOCAL_ID));


-- TIPO_MOVIMIENTO_ALMACEN definition

-- Drop table

-- DROP TABLE TIPO_MOVIMIENTO_ALMACEN;

CREATE TABLE TIPO_MOVIMIENTO_ALMACEN ( ID_MOVIMIENTO NUMERIC(3,0) NOT NULL, DESCRIPCION VARCHAR(50), TIPO_MOVIMIENTO VARCHAR(1), CONSTRAINT PK_TIPO_MOVIMIENTO_ALMACEN PRIMARY KEY (ID_MOVIMIENTO));


-- VENTAS_POLVO definition

-- Drop table

-- DROP TABLE VENTAS_POLVO;

CREATE TABLE VENTAS_POLVO ( MES_PERIODO NUMERIC(2,0) NOT NULL, ANIO_PERIODO NUMERIC(4,0) NOT NULL, LECHER NUMERIC(10,0) NOT NULL, EXTENSION NUMERIC(2,0), DIAS_VENTA NUMERIC(2,0), VENTA NUMERIC(10,0), SURTIMIENTO NUMERIC(10,0), INVENTARIO_FINAL NUMERIC(10,0), INVENTARIO_INICIAL NUMERIC(10,0), VENTA_LIBRO_RETIRO NUMERIC(10,0), NOMBRE_ARCHIVO_CARGADO VARCHAR(60), USUARIO_REGISTRADOR VARCHAR(40), FECHA_HORA_APLICACION TIMESTAMP, CONSTRAINT PK_VENTAS_POLVO PRIMARY KEY (MES_PERIODO,ANIO_PERIODO,LECHER));


-- COMPORTAMIENTO_VENTA definition

-- Drop table

-- DROP TABLE COMPORTAMIENTO_VENTA;

CREATE TABLE COMPORTAMIENTO_VENTA ( MES_PERIODO NUMERIC(2,0) NOT NULL, ANIO_PERIODO NUMERIC(4,0) NOT NULL, LECHER NUMERIC(10,0) NOT NULL, CVE_PRODUCTO VARCHAR(11) NOT NULL, PAD_FAMILIAS NUMERIC(5,0), PAD_MENORES NUMERIC(5,0), PAD_MAYORES NUMERIC(5,0), DOTACION_SOLICITADA_PROM_DIARIO NUMERIC(5,3), DOTACION_MENSUAL_TEORICA NUMERIC(5,0), TOTAL_VENTAS NUMERIC(6,2), PROCENTAJE_VENTAS_VS_SOLICITADO NUMERIC(6,3), VENTAS_MES_ANTERIOR NUMERIC(5,0), PORCENTAJE_VENTAS_MES_ANTERIOR FLOAT, FACTOR_RETIRO FLOAT, LITROS_BENEF_MES FLOAT, DIFERENCIA_LITROS FLOAT, PROMEDIO_VENTAS_DIA NUMERIC(6,3), TOTAL_DOTACION NUMERIC(5,0), TOTAL_ROTOS NUMERIC(9,0), TOTAL_FALTANTES NUMERIC(5,0), TOTAL_SOBRANTES NUMERIC(5,0), TOTAL_TRASPASO NUMERIC(5,0), TOTAL_DEVOLUCION NUMERIC(5,0), TOTAL_DEGUSTACION NUMERIC(5,0), CIERRE_DEFINITIVO NUMERIC(1,0), FECHA_TOMA_INVENTARIO DATE, INVENTARIO_INICIAL NUMERIC(8,0), INVENTARIO_FINAL NUMERIC(8,0), VENTA_LIBRO_RETIRO NUMERIC(8,0), DIAS_VENTA_EXISTENCIA_FINAL NUMERIC(3,0), CONSTRAINT INTEG_241 PRIMARY KEY (MES_PERIODO,ANIO_PERIODO,LECHER,CVE_PRODUCTO), CONSTRAINT INTEG_268 FOREIGN KEY (CVE_PRODUCTO) REFERENCES PRODUCTO(CVE_PRODUCTO));
CREATE INDEX RDB$FOREIGN32 ON COMPORTAMIENTO_VENTA (CVE_PRODUCTO);
CREATE UNIQUE INDEX RDB$PRIMARY5 ON COMPORTAMIENTO_VENTA (MES_PERIODO,ANIO_PERIODO,LECHER,CVE_PRODUCTO);


-- DIAS_NO_VENTA definition

-- Drop table

-- DROP TABLE DIAS_NO_VENTA;

CREATE TABLE DIAS_NO_VENTA ( ANIO_PERIODO NUMERIC(4,0) NOT NULL, MES_PERIODO NUMERIC(2,0) NOT NULL, FECHA_NO_VENTA DATE NOT NULL, MOTIVO BLOB SUB_TYPE TEXT, APLICADO NUMERIC(1,0), CONCEPTO_APLICACION VARCHAR(60), DESCRIPCION_APLICACION VARCHAR(60), PORCENTAJE_DISMINUCION_DOTACION NUMERIC(3,0), CLAVE_CONTRATO NUMERIC(1,0), CONSTRAINT INTEG_245 PRIMARY KEY (MES_PERIODO,ANIO_PERIODO,FECHA_NO_VENTA), CONSTRAINT FK_DIAS_NO_VENTA_1 FOREIGN KEY (CLAVE_CONTRATO) REFERENCES CONTRATO(CLAVE_CONTRATO));
CREATE INDEX FK_DIAS_NO_VENTA_1 ON DIAS_NO_VENTA (CLAVE_CONTRATO);
CREATE UNIQUE INDEX RDB$PRIMARY9 ON DIAS_NO_VENTA (MES_PERIODO,ANIO_PERIODO,FECHA_NO_VENTA);


-- EMPLEADO definition

-- Drop table

-- DROP TABLE EMPLEADO;

CREATE TABLE EMPLEADO ( NUMERO_NOMINA NUMERIC(5,0) NOT NULL, NOMBRE VARCHAR(60), CLAVE_PUESTO NUMERIC(5,0), CLAVE_AREA NUMERIC(5,0), DIRECCION_EMAIL VARCHAR(30), CONSTRAINT INTEG_246 PRIMARY KEY (NUMERO_NOMINA), CONSTRAINT INTEG_278 FOREIGN KEY (CLAVE_PUESTO) REFERENCES PUESTO(CLAVE_PUESTO), CONSTRAINT INTEG_279 FOREIGN KEY (CLAVE_PUESTO) REFERENCES PUESTO(CLAVE_PUESTO), CONSTRAINT INTEG_280 FOREIGN KEY (CLAVE_PUESTO) REFERENCES PUESTO(CLAVE_PUESTO));
CREATE INDEX RDB$FOREIGN42 ON EMPLEADO (CLAVE_PUESTO);
CREATE INDEX RDB$FOREIGN43 ON EMPLEADO (CLAVE_PUESTO);
CREATE INDEX RDB$FOREIGN44 ON EMPLEADO (CLAVE_PUESTO);
CREATE UNIQUE INDEX RDB$PRIMARY10 ON EMPLEADO (NUMERO_NOMINA);


-- FOL_ENTREGA_FOLIO_BLANCO definition

-- Drop table

-- DROP TABLE FOL_ENTREGA_FOLIO_BLANCO;

CREATE TABLE FOL_ENTREGA_FOLIO_BLANCO ( EFB_CONSECUTIVO NUMERIC(10,0) NOT NULL, EFB_FECHA_ENTREGA DATE NOT NULL, EFB_FOLIO_INICIAL NUMERIC(11,0), EFB_FOLIO_FINAL NUMERIC(11,0), EFB_PROMOTOR_CLAVE NUMERIC(3,0) NOT NULL, EFB_USUARIO_REGISTRADOR CHAR(18), EFB_USUARIO_ACTUALIZADOR CHAR(18), EFB_FECHA_HORA_ACTUALIZACION TIMESTAMP, EFB_FECHA_HORA_REGISTRO TIMESTAMP, EFB_FOLIOS_REGISTRADOS NUMERIC(1,0), EFB_OFICIO_REFERENCIA VARCHAR(30), CONSTRAINT PK_ENTREGA_FOLIO_BLANCO PRIMARY KEY (EFB_CONSECUTIVO), CONSTRAINT INTEG_288 FOREIGN KEY (EFB_PROMOTOR_CLAVE) REFERENCES PROMOTOR(PMT_NUMERO));
CREATE INDEX RDB$FOREIGN52 ON FOL_ENTREGA_FOLIO_BLANCO (EFB_PROMOTOR_CLAVE);


-- FOL_ESTATUS_FOLIO definition

-- Drop table

-- DROP TABLE FOL_ESTATUS_FOLIO;

CREATE TABLE FOL_ESTATUS_FOLIO ( TIPO_FOLIO_CLAVE NUMERIC(5,0) NOT NULL, ESTATUS_FOLIO_CLAVE NUMERIC(5,0) NOT NULL, ESTATUS_FOLIO_DESCRIPCION CHAR(50), ESTATUS_FOLIO_CONTABILIZAR CHAR(1), CONSTRAINT PK_ESTATUS_FOLIO PRIMARY KEY (TIPO_FOLIO_CLAVE,ESTATUS_FOLIO_CLAVE), CONSTRAINT FK_ESTATUS_FOLIO_1 FOREIGN KEY (TIPO_FOLIO_CLAVE) REFERENCES FOL_TIPO_FOLIO(TIPO_FOLIO_CLAVE));
CREATE INDEX FK_ESTATUS_FOLIO_1 ON FOL_ESTATUS_FOLIO (TIPO_FOLIO_CLAVE);


-- MENU_ITEMS definition

-- Drop table

-- DROP TABLE MENU_ITEMS;

CREATE TABLE MENU_ITEMS ( ID_MENU NUMERIC(3,0) NOT NULL, ID_ITEM NUMERIC(3,0) NOT NULL, ITEM_DESCRIPCION VARCHAR(60), HABILITADO VARCHAR(6), CONSTRAINT PK_MENU_ITEMS PRIMARY KEY (ID_MENU,ID_ITEM), CONSTRAINT FK_MENU_ITEMS_1 FOREIGN KEY (ID_MENU) REFERENCES MENU_TIPO_NIVEL(ID_MENU));
CREATE INDEX FK_MENU_ITEMS_1 ON MENU_ITEMS (ID_MENU);


-- MUNICIPIO definition

-- Drop table

-- DROP TABLE MUNICIPIO;

CREATE TABLE MUNICIPIO ( EFD_NUMERO NUMERIC(2,0) NOT NULL, MUN_NUMERO NUMERIC(3,0) NOT NULL, MUN_DESCRIPCION VARCHAR(60), CONSTRAINT INTEG_254 PRIMARY KEY (MUN_NUMERO,EFD_NUMERO), CONSTRAINT INTEG_313 FOREIGN KEY (EFD_NUMERO) REFERENCES ENTIDAD(EFD_NUMERO), CONSTRAINT INTEG_314 FOREIGN KEY (EFD_NUMERO) REFERENCES ENTIDAD(EFD_NUMERO), CONSTRAINT INTEG_315 FOREIGN KEY (EFD_NUMERO) REFERENCES ENTIDAD(EFD_NUMERO));
CREATE INDEX RDB$FOREIGN77 ON MUNICIPIO (EFD_NUMERO);
CREATE INDEX RDB$FOREIGN78 ON MUNICIPIO (EFD_NUMERO);
CREATE INDEX RDB$FOREIGN79 ON MUNICIPIO (EFD_NUMERO);
CREATE UNIQUE INDEX RDB$PRIMARY18 ON MUNICIPIO (MUN_NUMERO,EFD_NUMERO);


-- PBL_CAUSA_DETALLE definition

-- Drop table

-- DROP TABLE PBL_CAUSA_DETALLE;

CREATE TABLE PBL_CAUSA_DETALLE ( PBL_CAUSA_ID NUMERIC(2,0) NOT NULL, PBL_CAUSA_DET_ID NUMERIC(2,0) NOT NULL, PBL_CAUSA_DET_DESCRIP VARCHAR(60), PBL_CAUSA_DET_DIASPROB1 VARCHAR(1), PBL_CAUSA_DET_DIASPROB4 VARCHAR(1), PBL_CAUSA_DET_DIFLTS VARCHAR(1), PBL_CAUSA_DET_DESCRIP_LARG BLOB SUB_TYPE TEXT, CONSTRAINT PK_PBL_CAUSA_DETALLE PRIMARY KEY (PBL_CAUSA_DET_ID,PBL_CAUSA_ID), CONSTRAINT FK_PBL_CAUSA_DETALLE_1 FOREIGN KEY (PBL_CAUSA_ID) REFERENCES PBL_CAUSA(PBL_CAUSA_ID));
CREATE INDEX FK_PBL_CAUSA_DETALLE_1 ON PBL_CAUSA_DETALLE (PBL_CAUSA_ID);


-- PRECIO_PRODUCTO definition

-- Drop table

-- DROP TABLE PRECIO_PRODUCTO;

CREATE TABLE PRECIO_PRODUCTO ( CLAVE_CONTRATO NUMERIC(1,0) NOT NULL, CVE_PRODUCTO VARCHAR(11) NOT NULL, PRECIO_LITRO_PUBLICO NUMERIC(8,4), PRECIO_LITRO_CONCESIONARIO NUMERIC(8,4), PORCENTAJE_GANANCIA FLOAT, CONSTRAINT INTEG_257 PRIMARY KEY (CVE_PRODUCTO,CLAVE_CONTRATO), CONSTRAINT INTEG_316 FOREIGN KEY (CVE_PRODUCTO) REFERENCES PRODUCTO(CVE_PRODUCTO), CONSTRAINT INTEG_317 FOREIGN KEY (CLAVE_CONTRATO) REFERENCES CONTRATO(CLAVE_CONTRATO), CONSTRAINT INTEG_318 FOREIGN KEY (CVE_PRODUCTO) REFERENCES PRODUCTO(CVE_PRODUCTO), CONSTRAINT INTEG_319 FOREIGN KEY (CLAVE_CONTRATO) REFERENCES CONTRATO(CLAVE_CONTRATO), CONSTRAINT INTEG_320 FOREIGN KEY (CVE_PRODUCTO) REFERENCES PRODUCTO(CVE_PRODUCTO), CONSTRAINT INTEG_321 FOREIGN KEY (CLAVE_CONTRATO) REFERENCES CONTRATO(CLAVE_CONTRATO));
CREATE INDEX RDB$FOREIGN80 ON PRECIO_PRODUCTO (CVE_PRODUCTO);
CREATE INDEX RDB$FOREIGN81 ON PRECIO_PRODUCTO (CLAVE_CONTRATO);
CREATE INDEX RDB$FOREIGN82 ON PRECIO_PRODUCTO (CVE_PRODUCTO);
CREATE INDEX RDB$FOREIGN83 ON PRECIO_PRODUCTO (CLAVE_CONTRATO);
CREATE INDEX RDB$FOREIGN84 ON PRECIO_PRODUCTO (CVE_PRODUCTO);
CREATE INDEX RDB$FOREIGN85 ON PRECIO_PRODUCTO (CLAVE_CONTRATO);
CREATE UNIQUE INDEX RDB$PRIMARY21 ON PRECIO_PRODUCTO (CVE_PRODUCTO,CLAVE_CONTRATO);


-- RAMO_EMPRESARIAL definition

-- Drop table

-- DROP TABLE RAMO_EMPRESARIAL;

CREATE TABLE RAMO_EMPRESARIAL ( ID_CLASIFICACION NUMERIC(5,0) NOT NULL, ID_RAMO_EMPRESARIAL NUMERIC(5,0) NOT NULL, DESCRIPCION VARCHAR(60), CONSTRAINT PK_RAMO_EMPRESARIAL PRIMARY KEY (ID_RAMO_EMPRESARIAL,ID_CLASIFICACION), CONSTRAINT FK_RAMO_EMPRESARIAL_1 FOREIGN KEY (ID_CLASIFICACION) REFERENCES CLASIFICACION_EMPRESA(ID_CLASIFICACION));
CREATE INDEX FK_RAMO_EMPRESARIAL_1 ON RAMO_EMPRESARIAL (ID_CLASIFICACION);


-- REGISTRO_E_S definition

-- Drop table

-- DROP TABLE REGISTRO_E_S;

CREATE TABLE REGISTRO_E_S ( MOVIMIENTO_E_S VARCHAR(1) NOT NULL, FOLIO NUMERIC(10,0) NOT NULL, FECHA_FOLIO DATE, NOMBRE_RECIBE VARCHAR(60), RECIBI_DE VARCHAR(60), ID_DOCUMENTO VARCHAR(15), ID_PEDIDO NUMERIC(10,0), NOMBRE_AUTORIZO VARCHAR(60), NOMBRE_SOLICITA VARCHAR(60), NOMBRE_ENTREGADO VARCHAR(60), ID_CONCEPTO_E_S NUMERIC(3,0), OBSERVACIONES BLOB SUB_TYPE TEXT, DOCUMENTO VARCHAR(25), AFECTADO_KARDEX NUMERIC(1,0), CONSTRAINT PK_REGISTRO_E_S PRIMARY KEY (MOVIMIENTO_E_S,FOLIO), CONSTRAINT FK_REGISTRO_E_S_1 FOREIGN KEY (ID_CONCEPTO_E_S) REFERENCES TIPO_MOVIMIENTO_ALMACEN(ID_MOVIMIENTO));
CREATE INDEX FK_REGISTRO_E_S_1 ON REGISTRO_E_S (ID_CONCEPTO_E_S);


-- REGISTRO_E_S_DETALLE definition

-- Drop table

-- DROP TABLE REGISTRO_E_S_DETALLE;

CREATE TABLE REGISTRO_E_S_DETALLE ( MOVIMIENTO_E_S VARCHAR(1) NOT NULL, FOLIO NUMERIC(10,0) NOT NULL, CONSEC NUMERIC(5,0) NOT NULL, CVE_PRODUCTO VARCHAR(11), CANTIDAD_SOLICITADA NUMERIC(5,0), CANTIDAD_SURTIDA NUMERIC(5,0), UNIDAD_PRODUCTO VARCHAR(20), OBSERVACION VARCHAR(60), CONSTRAINT PK_REGISTRO_E_S_DETALLE PRIMARY KEY (MOVIMIENTO_E_S,FOLIO,CONSEC), CONSTRAINT FK_REGISTRO_E_S_DETALLE_1 FOREIGN KEY (MOVIMIENTO_E_S,FOLIO) REFERENCES REGISTRO_E_S(MOVIMIENTO_E_S,FOLIO), CONSTRAINT FK_REGISTRO_E_S_DETALLE_2 FOREIGN KEY (CVE_PRODUCTO) REFERENCES PRODUCTO(CVE_PRODUCTO));
CREATE INDEX FK_REGISTRO_E_S_DETALLE_1 ON REGISTRO_E_S_DETALLE (MOVIMIENTO_E_S,FOLIO);
CREATE INDEX FK_REGISTRO_E_S_DETALLE_2 ON REGISTRO_E_S_DETALLE (CVE_PRODUCTO);


-- REQUERIMIENTO_DETALLE definition

-- Drop table

-- DROP TABLE REQUERIMIENTO_DETALLE;

CREATE TABLE REQUERIMIENTO_DETALLE ( ID_REQUERIMIENTO NUMERIC(5,0) NOT NULL, ID_CONSEC NUMERIC(3,0) NOT NULL, CODIGO_PRODUCTO VARCHAR(11), CANTIDAD NUMERIC(3,0), CONSTRAINT PK_REQUERIMIENTO_DETALLE PRIMARY KEY (ID_REQUERIMIENTO,ID_CONSEC), CONSTRAINT FK_REQUERIMIENTO_DETALLE_1 FOREIGN KEY (ID_REQUERIMIENTO) REFERENCES REQUERIMIENTO(ID_REQUERIMIENTO), CONSTRAINT FK_REQUERIMIENTO_DETALLE_2 FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CVE_PRODUCTO));
CREATE INDEX FK_REQUERIMIENTO_DETALLE_1 ON REQUERIMIENTO_DETALLE (ID_REQUERIMIENTO);
CREATE INDEX FK_REQUERIMIENTO_DETALLE_2 ON REQUERIMIENTO_DETALLE (CODIGO_PRODUCTO);


-- RUBRO_CLASIFICACION definition

-- Drop table

-- DROP TABLE RUBRO_CLASIFICACION;

CREATE TABLE RUBRO_CLASIFICACION ( CLAVE_RUBRO NUMERIC(3,0) NOT NULL, CLAVE_CLASIFICACION NUMERIC(3,0) NOT NULL, DESCRIPCION VARCHAR(60), CONSTRAINT PK_RUBRO_CLASIFICACION PRIMARY KEY (CLAVE_RUBRO,CLAVE_CLASIFICACION), CONSTRAINT FK_RUBRO_CLASIFICACION_1 FOREIGN KEY (CLAVE_CLASIFICACION) REFERENCES CLASIFICACION(CLAVE_CLASIFICACION));
CREATE INDEX FK_RUBRO_CLASIFICACION_1 ON RUBRO_CLASIFICACION (CLAVE_CLASIFICACION);


-- TRANSPORTISTA definition

-- Drop table

-- DROP TABLE TRANSPORTISTA;

CREATE TABLE TRANSPORTISTA ( APELLIDO_PATERNO VARCHAR(60), CLAVE_TRANSPORTISTA NUMERIC(6,0) NOT NULL, APELLIDO_MATERNO VARCHAR(60), TELEFONO_CELULAR VARCHAR(15), TELEFONO_CASA VARCHAR(15), CLAVE_CIA NUMERIC(5,0), NOMBRE VARCHAR(60), CONSTRAINT INTEG_264 PRIMARY KEY (CLAVE_TRANSPORTISTA), CONSTRAINT INTEG_337 FOREIGN KEY (CLAVE_CIA) REFERENCES COMPANIA_TRANSPORTE(CLAVE_CIA), CONSTRAINT INTEG_338 FOREIGN KEY (CLAVE_CIA) REFERENCES COMPANIA_TRANSPORTE(CLAVE_CIA), CONSTRAINT INTEG_339 FOREIGN KEY (CLAVE_CIA) REFERENCES COMPANIA_TRANSPORTE(CLAVE_CIA));
CREATE INDEX RDB$FOREIGN101 ON TRANSPORTISTA (CLAVE_CIA);
CREATE INDEX RDB$FOREIGN102 ON TRANSPORTISTA (CLAVE_CIA);
CREATE INDEX RDB$FOREIGN103 ON TRANSPORTISTA (CLAVE_CIA);
CREATE UNIQUE INDEX RDB$PRIMARY28 ON TRANSPORTISTA (CLAVE_TRANSPORTISTA);


-- USUARIO definition

-- Drop table

-- DROP TABLE USUARIO;

CREATE TABLE USUARIO ( ID_USUARIO VARCHAR(20) NOT NULL, ID_MENU NUMERIC(3,0), CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO), CONSTRAINT FK_USUARIO_1 FOREIGN KEY (ID_MENU) REFERENCES MENU_TIPO_NIVEL(ID_MENU));
CREATE INDEX FK_USUARIO_1 ON USUARIO (ID_MENU);


-- VENTA_DETALLE definition

-- Drop table

-- DROP TABLE VENTA_DETALLE;

CREATE TABLE VENTA_DETALLE ( FOLIO_NOTA NUMERIC(10,0) NOT NULL, CVE_PRODUCTO VARCHAR(11) NOT NULL, CANTIDAD NUMERIC(5,0), PRECIO_UNITARIO NUMERIC(8,2), OBSERVACION VARCHAR(100), CONSTRAINT PK_VENTA_DETALLE PRIMARY KEY (FOLIO_NOTA,CVE_PRODUCTO), CONSTRAINT FK_VENTA_DETALLE_1 FOREIGN KEY (CVE_PRODUCTO) REFERENCES PRODUCTO(CVE_PRODUCTO));
CREATE INDEX FK_VENTA_DETALLE_1 ON VENTA_DETALLE (CVE_PRODUCTO);


-- CAMION definition

-- Drop table

-- DROP TABLE CAMION;

CREATE TABLE CAMION ( NECONOMICO NUMERIC(5,0) NOT NULL, MARCA VARCHAR(30), MODELO SMALLINT, PLACAS VARCHAR(7), CAPACIDAD INTEGER, CLAVE_TRANSPORTISTA NUMERIC(6,0) NOT NULL, NUMERO_EJES NUMERIC(2,0), CLAVE_TIPO_CAMION SMALLINT, CLAVE_CAJA SMALLINT, CLAVE_SUSPENSION SMALLINT, CONSTRAINT INTEG_239 PRIMARY KEY (NECONOMICO), CONSTRAINT FK_CAMION_1 FOREIGN KEY (CLAVE_TIPO_CAMION) REFERENCES TIPO_CAMION(CLAVE_TIPO_CAMION), CONSTRAINT FK_CAMION_2 FOREIGN KEY (CLAVE_CAJA) REFERENCES TIPO_CAJA(CLAVE_CAJA), CONSTRAINT FK_CAMION_3 FOREIGN KEY (CLAVE_SUSPENSION) REFERENCES SUSPENSION(CLAVE_SUSPENSION), CONSTRAINT INTEG_265 FOREIGN KEY (CLAVE_TRANSPORTISTA) REFERENCES TRANSPORTISTA(CLAVE_TRANSPORTISTA), CONSTRAINT INTEG_266 FOREIGN KEY (CLAVE_TRANSPORTISTA) REFERENCES TRANSPORTISTA(CLAVE_TRANSPORTISTA), CONSTRAINT INTEG_267 FOREIGN KEY (CLAVE_TRANSPORTISTA) REFERENCES TRANSPORTISTA(CLAVE_TRANSPORTISTA));
CREATE INDEX FK_CAMION_1 ON CAMION (CLAVE_TIPO_CAMION);
CREATE INDEX FK_CAMION_2 ON CAMION (CLAVE_CAJA);
CREATE INDEX FK_CAMION_3 ON CAMION (CLAVE_SUSPENSION);
CREATE INDEX RDB$FOREIGN29 ON CAMION (CLAVE_TRANSPORTISTA);
CREATE INDEX RDB$FOREIGN30 ON CAMION (CLAVE_TRANSPORTISTA);
CREATE INDEX RDB$FOREIGN31 ON CAMION (CLAVE_TRANSPORTISTA);
CREATE UNIQUE INDEX RDB$PRIMARY3 ON CAMION (NECONOMICO);


-- CLIENTE definition

-- Drop table

-- DROP TABLE CLIENTE;

CREATE TABLE CLIENTE ( ID_CLIENTE VARCHAR(10) NOT NULL, ID_CLASIFICACION NUMERIC(5,0) NOT NULL, ID_RAMO_EMPRESARIAL NUMERIC(5,0) NOT NULL, RAZON_SOCIAL VARCHAR(60) NOT NULL, CALLE_NUMERO_FISCAL VARCHAR(60) NOT NULL, COLONIA_FISCAL VARCHAR(60) NOT NULL, CIUDAD_FISCAL VARCHAR(60) NOT NULL, CODIGO_POSTAL_FISCAL VARCHAR(5) NOT NULL, RFC VARCHAR(13) NOT NULL, TELEFONO_1 VARCHAR(40) NOT NULL, CORREO_ELECTRONICO VARCHAR(60), TELEFONO_2 VARCHAR(40), CLAVE_TIPO_CONTRATO NUMERIC(5,0), DIAS_CREDITO NUMERIC(2,0), PORCENTAJE_DESCUENTO FLOAT, ALIAS_CLIENTE VARCHAR(50), NOMBRE_CONTACTO VARCHAR(60), OBSERVACIONES BLOB SUB_TYPE TEXT, CLAVE_RUTA_LC NUMERIC(5,0), SECUENCIA_DISTRIBUCION NUMERIC(3,0), CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE), CONSTRAINT FK_CLIENTE_1 FOREIGN KEY (ID_RAMO_EMPRESARIAL,ID_CLASIFICACION) REFERENCES RAMO_EMPRESARIAL(ID_RAMO_EMPRESARIAL,ID_CLASIFICACION));
CREATE INDEX FK_CLIENTE_1 ON CLIENTE (ID_RAMO_EMPRESARIAL,ID_CLASIFICACION);


-- LOCALIDAD definition

-- Drop table

-- DROP TABLE LOCALIDAD;

CREATE TABLE LOCALIDAD ( EFD_NUMERO NUMERIC(2,0) NOT NULL, MUN_NUMERO NUMERIC(3,0) NOT NULL, LOC_NUMERO NUMERIC(4,0) NOT NULL, LOC_DESCRIPCION VARCHAR(60), CONSTRAINT INTEG_253 PRIMARY KEY (LOC_NUMERO,MUN_NUMERO,EFD_NUMERO), CONSTRAINT INTEG_310 FOREIGN KEY (MUN_NUMERO,EFD_NUMERO) REFERENCES MUNICIPIO(MUN_NUMERO,EFD_NUMERO), CONSTRAINT INTEG_311 FOREIGN KEY (MUN_NUMERO,EFD_NUMERO) REFERENCES MUNICIPIO(MUN_NUMERO,EFD_NUMERO), CONSTRAINT INTEG_312 FOREIGN KEY (MUN_NUMERO,EFD_NUMERO) REFERENCES MUNICIPIO(MUN_NUMERO,EFD_NUMERO));
CREATE INDEX RDB$FOREIGN74 ON LOCALIDAD (MUN_NUMERO,EFD_NUMERO);
CREATE INDEX RDB$FOREIGN75 ON LOCALIDAD (MUN_NUMERO,EFD_NUMERO);
CREATE INDEX RDB$FOREIGN76 ON LOCALIDAD (MUN_NUMERO,EFD_NUMERO);
CREATE UNIQUE INDEX RDB$PRIMARY17 ON LOCALIDAD (LOC_NUMERO,MUN_NUMERO,EFD_NUMERO);


-- PEDIDO definition

-- Drop table

-- DROP TABLE PEDIDO;

CREATE TABLE PEDIDO ( ID_PEDIDO NUMERIC(10,0) NOT NULL, FECHA_PEDIDO DATE NOT NULL, FECHA_HORA_REGISTRO TIMESTAMP, ID_CLIENTE VARCHAR(10) NOT NULL, ESTATUS_PEDIDO NUMERIC(3,0), USUARIO_REGISTRADOR VARCHAR(10), OBSERVACIONES BLOB SUB_TYPE TEXT, IMAGEN_PEDIDO BLOB SUB_TYPE BINARY, FECHA_PROBABLE_SURTIMIENTO DATE NOT NULL, PATH_SOPORTE_DOCUMENTAL VARCHAR(300), ESTATUS_PEDIDO_DESCRIPCION VARCHAR(40), TOTAL_PRODUCTOS_SOLICITADOS NUMERIC(3,0), TOTAL_PRODUCTOS_FACTURADOS NUMERIC(3,0), NOMBRE_SOLICITANTE_PEDIDO VARCHAR(60), ID_FACTURA VARCHAR(10), OBSERVACIONES_CREDITO BLOB SUB_TYPE TEXT, SALDO_TOTAL NUMERIC(14,2), SALIDA_REGISTRADA NUMERIC(1,0), CLAVE_RUTA_LC NUMERIC(5,0), RUTA_ARCHIVO_FACTURA VARCHAR(200), SURTIDO VARCHAR(1), OBSERVACION_NO_SURTIMIENTO BLOB SUB_TYPE TEXT, ID_PEDIDO_CLIENTE VARCHAR(10), CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO), CONSTRAINT FK_PEDIDO_1 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE));
CREATE INDEX FK_PEDIDO_1 ON PEDIDO (ID_CLIENTE);


-- PEDIDO_DETALLE definition

-- Drop table

-- DROP TABLE PEDIDO_DETALLE;

CREATE TABLE PEDIDO_DETALLE ( ID_PEDIDO NUMERIC(10,0) NOT NULL, CONSECUTIVO NUMERIC(5,0) NOT NULL, CVE_PRODUCTO VARCHAR(12) NOT NULL, CANTIDAD NUMERIC(5,0) NOT NULL, ESTATUS_ITEM_DISTRIBU VARCHAR(10), ESTATUS_ITEM_COBRANZA VARCHAR(10), OBSERVACION_ITEM_DISTRIBUCION VARCHAR(60), OBSERVACION_ITEM_COBRANZA VARCHAR(60), SALDO_PRODUCTO NUMERIC(14,4), LUN_CANASTILLAS NUMERIC(2,0), MAR_CANASTILLAS NUMERIC(2,0), MIE_CANASTILLAS NUMERIC(2,0), JUE_CANASTILLAS NUMERIC(2,0), VIE_CANASTILLAS NUMERIC(2,0), SAB_CANASTILLAS NUMERIC(2,0), FECHA_INICIO_APLICA DATE, FECHA_FIN_APLICA DATE, CONSTRAINT PK_PEDIDO_DETALLE PRIMARY KEY (ID_PEDIDO,CONSECUTIVO), CONSTRAINT FK_PEDIDO_DETALLE_1 FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO), CONSTRAINT FK_PEDIDO_DETALLE_2 FOREIGN KEY (CVE_PRODUCTO) REFERENCES PRODUCTO(CVE_PRODUCTO));
CREATE INDEX FK_PEDIDO_DETALLE_1 ON PEDIDO_DETALLE (ID_PEDIDO);
CREATE INDEX FK_PEDIDO_DETALLE_2 ON PEDIDO_DETALLE (CVE_PRODUCTO);


-- PROGRAMA_DISTRIBUCION_ANUAL definition

-- Drop table

-- DROP TABLE PROGRAMA_DISTRIBUCION_ANUAL;

CREATE TABLE PROGRAMA_DISTRIBUCION_ANUAL ( ANIO NUMERIC(4,0) NOT NULL, CLAVE_CLASIFICACION NUMERIC(3,0) NOT NULL, CLAVE_RUBRO NUMERIC(3,0) NOT NULL, OFICIO_REFERENCIA VARCHAR(20), ENE NUMERIC(15,3), FEB NUMERIC(15,3), MAR NUMERIC(15,3), ABR NUMERIC(15,3), MYO NUMERIC(15,3), JUN NUMERIC(15,3), JUL NUMERIC(15,3), AGO NUMERIC(15,3), SEP NUMERIC(15,3), OCT NUMERIC(15,3), NOV NUMERIC(15,3), DIC NUMERIC(15,3), CONSTRAINT PK_PROGRAMA_DISTRIBUCION_ANUAL PRIMARY KEY (ANIO,CLAVE_CLASIFICACION,CLAVE_RUBRO), CONSTRAINT FK_PROGRAMA_DISTRIBUCION_ANUAL FOREIGN KEY (CLAVE_RUBRO,CLAVE_CLASIFICACION) REFERENCES RUBRO_CLASIFICACION(CLAVE_RUBRO,CLAVE_CLASIFICACION));
CREATE INDEX FK_PROGRAMA_DISTRIBUCION_ANUAL ON PROGRAMA_DISTRIBUCION_ANUAL (CLAVE_RUBRO,CLAVE_CLASIFICACION);


-- RUTA definition

-- Drop table

-- DROP TABLE RUTA;

CREATE TABLE RUTA ( CLAVE_RUTA NUMERIC(5,0) NOT NULL, DESCRIPCION VARCHAR(60), CLAVE_RUTA_REPARTIDOR INTEGER, NECONOMICO NUMERIC(5,0), FECHA_APLICACION_REPARTIDOR DATE, ID_SUPERVISOR NUMERIC(5,0), CONSTRAINT INTEG_262 PRIMARY KEY (CLAVE_RUTA), CONSTRAINT FK_RUTA_1 FOREIGN KEY (ID_SUPERVISOR) REFERENCES SUPERVISOR(ID_SUPERVISOR), CONSTRAINT INTEG_331 FOREIGN KEY (NECONOMICO) REFERENCES CAMION(NECONOMICO), CONSTRAINT INTEG_332 FOREIGN KEY (CLAVE_RUTA_REPARTIDOR) REFERENCES RUTA_REPARTIDOR(CLAVE_RUTA_REPARTIDOR), CONSTRAINT INTEG_333 FOREIGN KEY (NECONOMICO) REFERENCES CAMION(NECONOMICO), CONSTRAINT INTEG_334 FOREIGN KEY (CLAVE_RUTA_REPARTIDOR) REFERENCES RUTA_REPARTIDOR(CLAVE_RUTA_REPARTIDOR), CONSTRAINT INTEG_335 FOREIGN KEY (NECONOMICO) REFERENCES CAMION(NECONOMICO), CONSTRAINT INTEG_336 FOREIGN KEY (CLAVE_RUTA_REPARTIDOR) REFERENCES RUTA_REPARTIDOR(CLAVE_RUTA_REPARTIDOR));
CREATE INDEX FK_RUTA_1 ON RUTA (ID_SUPERVISOR);
CREATE INDEX RDB$FOREIGN100 ON RUTA (CLAVE_RUTA_REPARTIDOR);
CREATE INDEX RDB$FOREIGN95 ON RUTA (NECONOMICO);
CREATE INDEX RDB$FOREIGN96 ON RUTA (CLAVE_RUTA_REPARTIDOR);
CREATE INDEX RDB$FOREIGN97 ON RUTA (NECONOMICO);
CREATE INDEX RDB$FOREIGN98 ON RUTA (CLAVE_RUTA_REPARTIDOR);
CREATE INDEX RDB$FOREIGN99 ON RUTA (NECONOMICO);
CREATE UNIQUE INDEX RDB$PRIMARY26 ON RUTA (CLAVE_RUTA);


-- RUTA_DISTRIBUCION definition

-- Drop table

-- DROP TABLE RUTA_DISTRIBUCION;

CREATE TABLE RUTA_DISTRIBUCION ( CLAVE_CIA NUMERIC(5,0) NOT NULL, CLAVE_RUTA NUMERIC(5,0) NOT NULL, DESCRIPCION VARCHAR(50), CLAVE_RUTA_REPARTIDOR NUMERIC(5,0), NECONOMICO NUMERIC(5,0), CONSTRAINT PK_RUTA_DISTRIBUCION PRIMARY KEY (CLAVE_CIA,CLAVE_RUTA), CONSTRAINT FK_RUTA_DISTRIBUCION_1 FOREIGN KEY (CLAVE_CIA) REFERENCES COMPANIA_TRANSPORTE(CLAVE_CIA), CONSTRAINT FK_RUTA_DISTRIBUCION_2 FOREIGN KEY (CLAVE_RUTA_REPARTIDOR) REFERENCES RUTA_REPARTIDOR(CLAVE_RUTA_REPARTIDOR), CONSTRAINT FK_RUTA_DISTRIBUCION_3 FOREIGN KEY (NECONOMICO) REFERENCES CAMION(NECONOMICO));
CREATE INDEX FK_RUTA_DISTRIBUCION_1 ON RUTA_DISTRIBUCION (CLAVE_CIA);
CREATE INDEX FK_RUTA_DISTRIBUCION_2 ON RUTA_DISTRIBUCION (CLAVE_RUTA_REPARTIDOR);
CREATE INDEX FK_RUTA_DISTRIBUCION_3 ON RUTA_DISTRIBUCION (NECONOMICO);


-- VENTA definition

-- Drop table

-- DROP TABLE VENTA;

CREATE TABLE VENTA ( FOLIO_NOTA NUMERIC(10,0) NOT NULL, ID_CLIENTE VARCHAR(10), TELEFONO VARCHAR(30), DOMICILIO VARCHAR(60), COLONIA VARCHAR(60), CIUDAD VARCHAR(40), CODIGO_POSTAL NUMERIC(5,0), OBSERVACIONES BLOB SUB_TYPE TEXT, FECHA_HORA_REGISTRO TIMESTAMP, USUARIO_REGISTRADOR VARCHAR(50), USUARIO_ACTUALIZADOR VARCHAR(50), FECHA_HORA_ACTUALIZACION TIMESTAMP, FOLIO_RECIBO_PAGO NUMERIC(8,0), VENTA_CANCELADA VARCHAR(1), NOMBRE_COMPRADOR_CLIENTE VARCHAR(60), CONSTRAINT PK_VENTA PRIMARY KEY (FOLIO_NOTA), CONSTRAINT FK_VENTA_1 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE));
CREATE INDEX FK_VENTA_1 ON VENTA (ID_CLIENTE);


-- DESPACHO definition

-- Drop table

-- DROP TABLE DESPACHO;

CREATE TABLE DESPACHO ( CVE_PRODUCTO VARCHAR(11) NOT NULL, CLAVE_RUTA NUMERIC(5,0) NOT NULL, FECHA_ENVIO DATE NOT NULL, FECHA_ELABORACION DATE, LITROS_AUTORIZADOS NUMERIC(10,0), CLAVE_PLANTA NUMERIC(5,0), LITROS NUMERIC(9,0), OBSERVACIONES VARCHAR(300), CONSTRAINT INTEG_244 PRIMARY KEY (CLAVE_RUTA,CVE_PRODUCTO,FECHA_ENVIO), CONSTRAINT INTEG_269 FOREIGN KEY (CLAVE_RUTA) REFERENCES RUTA(CLAVE_RUTA), CONSTRAINT INTEG_270 FOREIGN KEY (CLAVE_PLANTA) REFERENCES PLANTA(CLAVE_PLANTA), CONSTRAINT INTEG_271 FOREIGN KEY (CVE_PRODUCTO) REFERENCES PRODUCTO(CVE_PRODUCTO), CONSTRAINT INTEG_272 FOREIGN KEY (CLAVE_RUTA) REFERENCES RUTA(CLAVE_RUTA), CONSTRAINT INTEG_273 FOREIGN KEY (CLAVE_PLANTA) REFERENCES PLANTA(CLAVE_PLANTA), CONSTRAINT INTEG_274 FOREIGN KEY (CVE_PRODUCTO) REFERENCES PRODUCTO(CVE_PRODUCTO), CONSTRAINT INTEG_275 FOREIGN KEY (CLAVE_RUTA) REFERENCES RUTA(CLAVE_RUTA), CONSTRAINT INTEG_276 FOREIGN KEY (CLAVE_PLANTA) REFERENCES PLANTA(CLAVE_PLANTA), CONSTRAINT INTEG_277 FOREIGN KEY (CVE_PRODUCTO) REFERENCES PRODUCTO(CVE_PRODUCTO));
CREATE INDEX RDB$FOREIGN33 ON DESPACHO (CLAVE_RUTA);
CREATE INDEX RDB$FOREIGN34 ON DESPACHO (CLAVE_PLANTA);
CREATE INDEX RDB$FOREIGN35 ON DESPACHO (CVE_PRODUCTO);
CREATE INDEX RDB$FOREIGN36 ON DESPACHO (CLAVE_RUTA);
CREATE INDEX RDB$FOREIGN37 ON DESPACHO (CLAVE_PLANTA);
CREATE INDEX RDB$FOREIGN38 ON DESPACHO (CVE_PRODUCTO);
CREATE INDEX RDB$FOREIGN39 ON DESPACHO (CLAVE_RUTA);
CREATE INDEX RDB$FOREIGN40 ON DESPACHO (CLAVE_PLANTA);
CREATE INDEX RDB$FOREIGN41 ON DESPACHO (CVE_PRODUCTO);
CREATE UNIQUE INDEX RDB$PRIMARY8 ON DESPACHO (CLAVE_RUTA,CVE_PRODUCTO,FECHA_ENVIO);


-- LECHERIA definition

-- Drop table

-- DROP TABLE LECHERIA;

CREATE TABLE LECHERIA ( LECHER NUMERIC(10,0) NOT NULL, EFD_NUMERO NUMERIC(2,0), MUN_NUMERO NUMERIC(3,0), LOC_NUMERO NUMERIC(4,0), CVE_PAS NUMERIC(5,0), AGEB CHAR(5), ML_CALLE CHAR(40), ML_COLO CHAR(40), ML_REFE CHAR(60), CPOSTAL NUMERIC(5,0), NOMBRELECH VARCHAR(40), AMBITO NUMERIC(1,0), ML_TVENTA NUMERIC(1,0), ML_TLECH NUMERIC(1,0), ML_LOCA NUMERIC(2,0), ML_RENT VARCHAR(8), TIPO_CONTR NUMERIC(1,0), FINICONTR VARCHAR(8), ML_FEI VARCHAR(8), TURNO CHAR(1), TMATINI CHAR(5), TMATFIN CHAR(5), TVESINI CHAR(5), TVESFIN CHAR(5), TIPODOTA CHAR(1), FROPERA NUMERIC(2,0), FRSURTI NUMERIC(2,0), RESSURTI NUMERIC(1,0), DIASOPER CHAR(7), CC_FAM NUMERIC(5,0), CC_BT1 NUMERIC(5,0), CC_BT2 NUMERIC(5,0), CC_BT3 NUMERIC(5,0), CC_BT4 NUMERIC(5,0), CC_BT5 NUMERIC(5,0), CC_BT6 NUMERIC(5,0), CC_BT7 NUMERIC(5,0), CL_FAM NUMERIC(5,0), CL_BEN NUMERIC(5,0), CL_HT1 NUMERIC(5,0), CL_MT1 NUMERIC(5,0), CL_HT2 NUMERIC(5,0), CL_BT2 NUMERIC(5,0), CL_HT3 NUMERIC(5,0), CL_MT3 NUMERIC(5,0), CL_HT4 NUMERIC(5,0), CL_MT4 NUMERIC(5,0), CL_HT5 NUMERIC(5,0), CL_BT5 NUMERIC(5,0), CL_HT6 NUMERIC(5,0), CL_BT6 NUMERIC(5,0), CL_HT7 NUMERIC(5,0), CL_BT7 NUMERIC(5,0), CL_H_5 NUMERIC(5,0), CL_M_5 NUMERIC(5,0), CL_H6A11 NUMERIC(5,0), CL_M6A11 NUMERIC(5,0), CL_H12A15 NUMERIC(5,0), CL_M12A15 NUMERIC(5,0), CL_H16A44 NUMERIC(5,0), CL_M16A44 NUMERIC(5,0), CL_H45A60 NUMERIC(5,0), CL_M45A60 NUMERIC(5,0), CL_H61_ NUMERIC(5,0), CL_M61_ NUMERIC(5,0), CAMPO_SABE NUMERIC(10,0), DOTAASIG NUMERIC(8,0), BENEASIG NUMERIC(5,0), MARGLECH NUMERIC(1,0), PROMOTOR NUMERIC(6,0), CLAVE_CONCESIONARIO NUMERIC(6,0), PRIORIDAD_DISTRIBUCION SMALLINT, FECHA_ACTUALIZACION DATE, EN_OPERACION SMALLINT, MES_PERIODO NUMERIC(2,0), ANIO_PERIODO NUMERIC(4,0), CLAVE_RUTA NUMERIC(5,0), TELEFONO_LECHERIA VARCHAR(20), CLAVE_ALMACEN NUMERIC(5,0), TIPO_PUNTO_VENTA NUMERIC(2,0), LATITUD DECIMAL(9,6), LONGITUD DECIMAL(9,6), CONSTRAINT INTEG_251 PRIMARY KEY (LECHER), CONSTRAINT FK_LECHERIA_1 FOREIGN KEY (PROMOTOR) REFERENCES PROMOTOR(PMT_NUMERO), CONSTRAINT FK_LECHERIA_2 FOREIGN KEY (CLAVE_ALMACEN) REFERENCES ALMACEN_DICONSA(CLAVE_ALMACEN), CONSTRAINT INTEG_292 FOREIGN KEY (CLAVE_RUTA) REFERENCES RUTA(CLAVE_RUTA), CONSTRAINT INTEG_293 FOREIGN KEY (LOC_NUMERO,MUN_NUMERO,EFD_NUMERO) REFERENCES LOCALIDAD(LOC_NUMERO,MUN_NUMERO,EFD_NUMERO), CONSTRAINT INTEG_294 FOREIGN KEY (TIPO_CONTR) REFERENCES CONTRATO(CLAVE_CONTRATO), CONSTRAINT INTEG_295 FOREIGN KEY (CVE_PAS) REFERENCES PAS(CVE_PAS), CONSTRAINT INTEG_296 FOREIGN KEY (CLAVE_CONCESIONARIO) REFERENCES CONCESIONARIO(CLAVE_CONCESIONARIO), CONSTRAINT INTEG_297 FOREIGN KEY (CLAVE_RUTA) REFERENCES RUTA(CLAVE_RUTA), CONSTRAINT INTEG_298 FOREIGN KEY (LOC_NUMERO,MUN_NUMERO,EFD_NUMERO) REFERENCES LOCALIDAD(LOC_NUMERO,MUN_NUMERO,EFD_NUMERO), CONSTRAINT INTEG_299 FOREIGN KEY (TIPO_CONTR) REFERENCES CONTRATO(CLAVE_CONTRATO), CONSTRAINT INTEG_300 FOREIGN KEY (CVE_PAS) REFERENCES PAS(CVE_PAS), CONSTRAINT INTEG_301 FOREIGN KEY (CLAVE_CONCESIONARIO) REFERENCES CONCESIONARIO(CLAVE_CONCESIONARIO), CONSTRAINT INTEG_302 FOREIGN KEY (CLAVE_RUTA) REFERENCES RUTA(CLAVE_RUTA), CONSTRAINT INTEG_303 FOREIGN KEY (LOC_NUMERO,MUN_NUMERO,EFD_NUMERO) REFERENCES LOCALIDAD(LOC_NUMERO,MUN_NUMERO,EFD_NUMERO), CONSTRAINT INTEG_304 FOREIGN KEY (TIPO_CONTR) REFERENCES CONTRATO(CLAVE_CONTRATO), CONSTRAINT INTEG_305 FOREIGN KEY (CVE_PAS) REFERENCES PAS(CVE_PAS), CONSTRAINT INTEG_306 FOREIGN KEY (CLAVE_CONCESIONARIO) REFERENCES CONCESIONARIO(CLAVE_CONCESIONARIO));
CREATE INDEX FK_LECHERIA_1 ON LECHERIA (PROMOTOR);
CREATE INDEX FK_LECHERIA_2 ON LECHERIA (CLAVE_ALMACEN);
CREATE INDEX RDB$FOREIGN56 ON LECHERIA (CLAVE_RUTA);
CREATE INDEX RDB$FOREIGN57 ON LECHERIA (LOC_NUMERO,MUN_NUMERO,EFD_NUMERO);
CREATE INDEX RDB$FOREIGN58 ON LECHERIA (TIPO_CONTR);
CREATE INDEX RDB$FOREIGN59 ON LECHERIA (CVE_PAS);
CREATE INDEX RDB$FOREIGN60 ON LECHERIA (CLAVE_CONCESIONARIO);
CREATE INDEX RDB$FOREIGN61 ON LECHERIA (CLAVE_RUTA);
CREATE INDEX RDB$FOREIGN62 ON LECHERIA (LOC_NUMERO,MUN_NUMERO,EFD_NUMERO);
CREATE INDEX RDB$FOREIGN63 ON LECHERIA (TIPO_CONTR);
CREATE INDEX RDB$FOREIGN64 ON LECHERIA (CVE_PAS);
CREATE INDEX RDB$FOREIGN65 ON LECHERIA (CLAVE_CONCESIONARIO);
CREATE INDEX RDB$FOREIGN66 ON LECHERIA (CLAVE_RUTA);
CREATE INDEX RDB$FOREIGN67 ON LECHERIA (LOC_NUMERO,MUN_NUMERO,EFD_NUMERO);
CREATE INDEX RDB$FOREIGN68 ON LECHERIA (TIPO_CONTR);
CREATE INDEX RDB$FOREIGN69 ON LECHERIA (CVE_PAS);
CREATE INDEX RDB$FOREIGN70 ON LECHERIA (CLAVE_CONCESIONARIO);
CREATE UNIQUE INDEX RDB$PRIMARY15 ON LECHERIA (LECHER);


-- LECHERIA_HISTORICO definition

-- Drop table

-- DROP TABLE LECHERIA_HISTORICO;

CREATE TABLE LECHERIA_HISTORICO ( LECHER NUMERIC(10,0) NOT NULL, CVE_PAS NUMERIC(5,0), EFD_NUMERO NUMERIC(2,0), MUN_NUMERO NUMERIC(3,0), LOC_NUMERO NUMERIC(4,0), AGEB CHAR(5), ML_CALLE CHAR(40), ML_COLO CHAR(40), ML_REFE CHAR(60), CPOSTAL NUMERIC(5,0), NOMBRELECH VARCHAR(40), AMBITO NUMERIC(1,0), ML_TVENTA NUMERIC(1,0), ML_TLECH NUMERIC(1,0), ML_LOCA NUMERIC(2,0), ML_RENT VARCHAR(8), TIPO_CONTR NUMERIC(1,0), FINICONTR VARCHAR(8), ML_FEI VARCHAR(8), TURNO CHAR(1), TMATINI CHAR(5), TMATFIN CHAR(5), TVESINI CHAR(5), TVESFIN CHAR(5), TIPODOTA CHAR(1), FROPERA NUMERIC(2,0), FRSURTI NUMERIC(2,0), RESSURTI NUMERIC(1,0), DIASOPER CHAR(7), CC_FAM NUMERIC(5,0), CC_BT1 NUMERIC(5,0), CC_BT2 NUMERIC(5,0), CC_BT3 NUMERIC(5,0), CC_BT4 NUMERIC(5,0), CC_BT5 NUMERIC(5,0), CC_BT6 NUMERIC(5,0), CC_BT7 NUMERIC(5,0), CL_FAM NUMERIC(5,0), CL_BEN NUMERIC(5,0), CL_HT1 NUMERIC(5,0), CL_MT1 NUMERIC(5,0), CL_HT2 NUMERIC(5,0), CL_BT2 NUMERIC(5,0), CL_HT3 NUMERIC(5,0), CL_MT3 NUMERIC(5,0), CL_HT4 NUMERIC(5,0), CL_MT4 NUMERIC(5,0), CL_HT5 NUMERIC(5,0), CL_BT5 NUMERIC(5,0), CL_HT6 NUMERIC(5,0), CL_BT6 NUMERIC(5,0), CL_HT7 NUMERIC(5,0), CL_BT7 NUMERIC(5,0), CL_H_5 NUMERIC(5,0), CL_M_5 NUMERIC(5,0), CL_H6A11 NUMERIC(5,0), CL_M6A11 NUMERIC(5,0), CL_H12A15 NUMERIC(5,0), CL_M12A15 NUMERIC(5,0), CL_H16A44 NUMERIC(5,0), CL_M16A44 NUMERIC(5,0), CL_H45A60 NUMERIC(5,0), CL_M45A60 NUMERIC(5,0), CL_H61_ NUMERIC(5,0), CL_M61_ NUMERIC(5,0), CAMPO_SABE NUMERIC(10,0), DOTAASIG NUMERIC(8,0), BENEASIG NUMERIC(5,0), MARGLECH NUMERIC(1,0), PROMOTOR NUMERIC(6,0), CLAVE_CONCESIONARIO NUMERIC(6,0), CLAVE_RUTA NUMERIC(5,0), PRIORIDAD_DISTRIBUCION SMALLINT, FECHA_ACTUALIZACION DATE, EN_OPERACION SMALLINT, MES_PERIODO NUMERIC(2,0) NOT NULL, ANIO_PERIODO NUMERIC(4,0) NOT NULL, LATITUD DECIMAL(9,6), LONGITUD DECIMAL(9,6), CLAVE_ALMACEN NUMERIC(5,0), TIPO_PUNTO_VENTA NUMERIC(2,0), TELEFONO_LECHERIA VARCHAR(60), CONSTRAINT INTEG_252 PRIMARY KEY (LECHER,MES_PERIODO,ANIO_PERIODO), CONSTRAINT INTEG_307 FOREIGN KEY (LECHER) REFERENCES LECHERIA(LECHER), CONSTRAINT INTEG_308 FOREIGN KEY (LECHER) REFERENCES LECHERIA(LECHER), CONSTRAINT INTEG_309 FOREIGN KEY (LECHER) REFERENCES LECHERIA(LECHER));
CREATE INDEX RDB$FOREIGN71 ON LECHERIA_HISTORICO (LECHER);
CREATE INDEX RDB$FOREIGN72 ON LECHERIA_HISTORICO (LECHER);
CREATE INDEX RDB$FOREIGN73 ON LECHERIA_HISTORICO (LECHER);
CREATE UNIQUE INDEX RDB$PRIMARY16 ON LECHERIA_HISTORICO (LECHER,MES_PERIODO,ANIO_PERIODO);


-- PROGRAMACION_SEMANAL definition

-- Drop table

-- DROP TABLE PROGRAMACION_SEMANAL;

CREATE TABLE PROGRAMACION_SEMANAL ( LECHER NUMERIC(10,0) NOT NULL, CVE_PRODUCTO VARCHAR(11) NOT NULL, LUN VARCHAR(1), MAR VARCHAR(1), MIE VARCHAR(1), JUE VARCHAR(1), VIE VARCHAR(1), SAB VARCHAR(1), DOM VARCHAR(1), SURTIR NUMERIC(1,0), LUN_CANASTILLAS SMALLINT, MAR_CANASTILLAS SMALLINT, MIE_CANASTILLAS SMALLINT, JUE_CANASTILLAS SMALLINT, VIE_CANASTILLAS SMALLINT, SAB_CANASTILLAS SMALLINT, DOM_CANASTILLAS INTEGER, CONSTRAINT INTEG_259 PRIMARY KEY (LECHER,CVE_PRODUCTO), CONSTRAINT INTEG_322 FOREIGN KEY (CVE_PRODUCTO) REFERENCES PRODUCTO(CVE_PRODUCTO), CONSTRAINT INTEG_323 FOREIGN KEY (LECHER) REFERENCES LECHERIA(LECHER), CONSTRAINT INTEG_324 FOREIGN KEY (CVE_PRODUCTO) REFERENCES PRODUCTO(CVE_PRODUCTO), CONSTRAINT INTEG_325 FOREIGN KEY (LECHER) REFERENCES LECHERIA(LECHER), CONSTRAINT INTEG_326 FOREIGN KEY (CVE_PRODUCTO) REFERENCES PRODUCTO(CVE_PRODUCTO), CONSTRAINT INTEG_327 FOREIGN KEY (LECHER) REFERENCES LECHERIA(LECHER));
CREATE INDEX RDB$FOREIGN86 ON PROGRAMACION_SEMANAL (CVE_PRODUCTO);
CREATE INDEX RDB$FOREIGN87 ON PROGRAMACION_SEMANAL (LECHER);
CREATE INDEX RDB$FOREIGN88 ON PROGRAMACION_SEMANAL (CVE_PRODUCTO);
CREATE INDEX RDB$FOREIGN89 ON PROGRAMACION_SEMANAL (LECHER);
CREATE INDEX RDB$FOREIGN90 ON PROGRAMACION_SEMANAL (CVE_PRODUCTO);
CREATE INDEX RDB$FOREIGN91 ON PROGRAMACION_SEMANAL (LECHER);
CREATE UNIQUE INDEX RDB$PRIMARY23 ON PROGRAMACION_SEMANAL (LECHER,CVE_PRODUCTO);


-- REPORTE_DAS30 definition

-- Drop table

-- DROP TABLE REPORTE_DAS30;

CREATE TABLE REPORTE_DAS30 ( FECHA_VENTA DATE NOT NULL, LECHER NUMERIC(10,0) NOT NULL, DOTACION_SUB NUMERIC(5,0), CANASTILLAS_SUB NUMERIC(5,0), CVE_CONCE INTEGER, NOMBRE_CONCESIONARIO VARCHAR(60), DOTACION_FRISIA NUMERIC(5,0), CANASTILLAS_FRISIA NUMERIC(5,0), CLAVE_RUTA INTEGER, PRECIO_SUBSIDIADA NUMERIC(8,4), PRECIO_FRISIA NUMERIC(8,4), COMENTARIO VARCHAR(200), COMENTARIO_INDIVIDUAL VARCHAR(200), MENSAJE_CONCESIONARIO BLOB SUB_TYPE TEXT, NOMBRE_OPERADOR VARCHAR(20), NUM_ECONOMICO NUMERIC(3,0), LINEA_TRANSPORTISTA VARCHAR(30), PRIORIDAD_DISTRIBUCION NUMERIC(2,0), FOLIO NUMERIC(10,0), CONSTRAINT INTEG_261 PRIMARY KEY (LECHER,FECHA_VENTA), CONSTRAINT INTEG_328 FOREIGN KEY (LECHER) REFERENCES LECHERIA(LECHER), CONSTRAINT INTEG_329 FOREIGN KEY (LECHER) REFERENCES LECHERIA(LECHER), CONSTRAINT INTEG_330 FOREIGN KEY (LECHER) REFERENCES LECHERIA(LECHER));
CREATE INDEX RDB$FOREIGN92 ON REPORTE_DAS30 (LECHER);
CREATE INDEX RDB$FOREIGN93 ON REPORTE_DAS30 (LECHER);
CREATE INDEX RDB$FOREIGN94 ON REPORTE_DAS30 (LECHER);
CREATE UNIQUE INDEX RDB$PRIMARY25 ON REPORTE_DAS30 (LECHER,FECHA_VENTA);


-- RUTA_LECHERIA definition

-- Drop table

-- DROP TABLE RUTA_LECHERIA;

CREATE TABLE RUTA_LECHERIA ( CLAVE_CIA NUMERIC(5,0) NOT NULL, CLAVE_RUTA NUMERIC(5,0) NOT NULL, LECHER NUMERIC(10,0) NOT NULL, SECUENCIA_DISTRIBUCION NUMERIC(4,0), KMS FLOAT, TIEMPO_RECORRIDO TIMESTAMP, TIEMPO_DESCARGAR TIMESTAMP, CLAVE_PLANTA NUMERIC(5,0), CONSTRAINT PK_RUTA_LECHERIA PRIMARY KEY (CLAVE_CIA,LECHER,CLAVE_RUTA), CONSTRAINT FK_RUTA_LECHERIA_1 FOREIGN KEY (CLAVE_CIA,CLAVE_RUTA) REFERENCES RUTA_DISTRIBUCION(CLAVE_CIA,CLAVE_RUTA), CONSTRAINT FK_RUTA_LECHERIA_2 FOREIGN KEY (LECHER) REFERENCES LECHERIA(LECHER), CONSTRAINT FK_RUTA_LECHERIA_3 FOREIGN KEY (CLAVE_CIA) REFERENCES COMPANIA_TRANSPORTE(CLAVE_CIA));
CREATE INDEX FK_RUTA_LECHERIA_1 ON RUTA_LECHERIA (CLAVE_CIA,CLAVE_RUTA);
CREATE INDEX FK_RUTA_LECHERIA_2 ON RUTA_LECHERIA (LECHER);
CREATE INDEX FK_RUTA_LECHERIA_3 ON RUTA_LECHERIA (CLAVE_CIA);


-- SOLICITUD_MERCANTIL definition

-- Drop table

-- DROP TABLE SOLICITUD_MERCANTIL;

CREATE TABLE SOLICITUD_MERCANTIL ( SOL_FOLIO NUMERIC(10,0) NOT NULL, SOL_FOTOGRAFIA BLOB SUB_TYPE BINARY, SOL_CLAVE_CONTRATO NUMERIC(1,0) NOT NULL, SOL_APELLIDO_PATERNO CHAR(60) NOT NULL, SOL_APELLIDO_MATERNO CHAR(60), SOL_NOMBRE CHAR(60) NOT NULL, SOL_CALLE CHAR(60) NOT NULL, SOL_NUMERO_EXTERIOR CHAR(5) NOT NULL, SOL_COLONIA CHAR(60) NOT NULL, SOL_REFERENCIA_UBICACION CHAR(100) NOT NULL, SOL_CLAVE_MUNICIPIO NUMERIC(3,0) NOT NULL, SOL_CLAVE_ENTIDAD NUMERIC(2,0) NOT NULL, SOL_CODIGO_POSTAL CHAR(5), SOL_TELEFONO_DOMICILIO CHAR(30) NOT NULL, SOL_TELEFONO_RECADOS CHAR(30), SOL_CLAVE_MPIO_NACIMIENTO NUMERIC(3,0) NOT NULL, SOL_CLAVE_ENT_NACIMIENTO NUMERIC(2,0) NOT NULL, SOL_FECHA_NACIMIENTO DATE NOT NULL, SOL_EDAD NUMERIC(2,0) NOT NULL, SOL_ESTADO_CIVIL CHAR(15) NOT NULL, SOL_ULTIMO_GRADO_ESTUDIOS CHAR(25) NOT NULL, SOL_CONSTANCIA_ESCOLAR CHAR(1), SOL_RFC CHAR(13) NOT NULL, SOL_PROPIETARIO_INMUEBLES CHAR(1) NOT NULL, SOL_TIPO_INMUEBLE_1 NUMERIC(2,0), SOL_UBICACION_INMUEBLE_1 CHAR(100), SOL_TIPO_INMUEBLE_2 NUMERIC(2,0), SOL_UBICACION_INMUEBLE_2 CHAR(100), SOL_TRABAJA_ACTUALMENTE CHAR(1) NOT NULL, SOL_HORA_INI_TRABAJA CHAR(5), SOL_HORA_FIN_TRABAJA CHAR(5), SOL_NOMBRE_CIA_TRABAJA CHAR(50), SOL_DOMICILIO_CIA_TRABAJA CHAR(50), SOL_TELEFONO_CIA_TRABAJA CHAR(30), SOL_PUESTO_CIA_TRABAJA CHAR(30), SOL_PUESTO_CIA_ANTIGUEDAD NUMERIC(2,0), SOL_COMPROMISO_1 CHAR(1) NOT NULL, SOL_COMPROMISO_2 CHAR(1) NOT NULL, SOL_COMPROMISO_3 CHAR(1) NOT NULL, SOL_COMPROMISO_4 CHAR(1) NOT NULL, SOL_EX_AGRAVIO_PERJUICIO CHAR(1), SOL_RAZON_SOCIAL_LOCAL CHAR(80) NOT NULL, SOL_CALLE_LOCAL CHAR(30) NOT NULL, SOL_NUMERO_EXT_LOCAL CHAR(5) NOT NULL, SOL_COLONIA_LOCAL CHAR(40) NOT NULL, SOL_REFERENCIAS_UBICACION_LOCAL CHAR(80) NOT NULL, SOL_MUNICIPIO_LOCAL NUMERIC(3,0) NOT NULL, SOL_ENTIDAD_LOCAL NUMERIC(2,0) NOT NULL, SOL_CODIGO_POSTAL_LOCAL CHAR(5), SOL_TELEFONO_DOMICILIO_LOCAL CHAR(30) NOT NULL, SOL_TELEFONO_RECADOS_LOCAL CHAR(30) NOT NULL, SOL_LUGAR_LLENADO CHAR(60) NOT NULL, SOL_FECHA_LLENADO DATE NOT NULL, SOL_DOCUMENTOS_ESCANEADOS BLOB SUB_TYPE BINARY, SOL_FECHA_HORA_REGISTRO TIMESTAMP, SOL_FECHA_HORA_ACTUALIZACION TIMESTAMP, SOL_AVAL_PATERNO CHAR(60) NOT NULL, SOL_AVAL_MATERNO CHAR(60), SOL_AVAL_NOMBRE CHAR(60) NOT NULL, SOL_AVAL_CALLE CHAR(30) NOT NULL, SOL_AVAL_NUMERO_EXTERIOR CHAR(5) NOT NULL, SOL_AVAL_COLONIA CHAR(50) NOT NULL, SOL_AVAL_REFERENCIA_UBICACION CHAR(100) NOT NULL, SOL_AVAL_MPIO NUMERIC(3,0) NOT NULL, SOL_AVAL_ENTIDAD NUMERIC(2,0) NOT NULL, SOL_AVAL_CODIGO_POSTAL CHAR(5), SOL_AVAL_TELEFONO_DOMICILIO CHAR(30) NOT NULL, SOL_AVAL_TELEFONO_RECADOS CHAR(30) NOT NULL, SOL_AVAL_TIPO_INMUEBLE NUMERIC(2,0) NOT NULL, SOL_AVAL_UBICACION_INMUEBLE CHAR(100) NOT NULL, SOL_AVAL_DOCUMENTOS_ESCANEADOS BLOB SUB_TYPE BINARY, SOL_DOC_COMPROBANTE_DOM CHAR(1), SOL_DOC_ID CHAR(1), SOL_DOC_FOTOGRAFIAS CHAR(1), SOL_DOC_ACTA_NACIMIENTO CHAR(1), SOL_DOC_CURP CHAR(1), SOL_DOC_PREDIAL CHAR(1), SOL_DOC_RFC_HACIENDA CHAR(1), SOL_DOC_TITULO_PROPIEDAD CHAR(1), SOL_AVAL_DOC_ID CHAR(1), SOL_AVAL_DOC_COMPROBANTE_DOM CHAR(1), SOL_AVAL_DOC_PREDIAL CHAR(1), SOL_AVAL_DOC_TITULO_PROPIEDAD CHAR(1), SOL_CLAVE_CONC_DISTR_ASIGNADO NUMERIC(5,0), SOL_FECHA_INICIO_OPERACIONES DATE NOT NULL, SOL_FECHA_FIN_OPERACIONES DATE NOT NULL, SOL_CLAVE_LECHERIA NUMERIC(10,0) NOT NULL, SOL_TIPO_GARANTIA NUMERIC(1,0) NOT NULL, SOL_ASEGURADORA_FIANZA VARCHAR(60), CONSTRAINT PK_SOLICITUD_MERCANTIL PRIMARY KEY (SOL_FOLIO), CONSTRAINT FK_SOLICITUD_MERCANTIL_1 FOREIGN KEY (SOL_CLAVE_LECHERIA) REFERENCES LECHERIA(LECHER));
CREATE INDEX FK_SOLICITUD_MERCANTIL_1 ON SOLICITUD_MERCANTIL (SOL_CLAVE_LECHERIA);


-- FOLIO definition

-- Drop table

-- DROP TABLE FOLIO;

CREATE TABLE FOLIO ( FOLIO_NUMERO NUMERIC(15,0) NOT NULL, FOLIO_NUMERO_TARJETA NUMERIC(5,0), FOLIO_NOMBRE_TITULAR CHAR(60), FOLIO_FECHA_IMPRESION DATE, FOLIO_FECHA_HORA_REGISTRO TIMESTAMP, FOLIO_USUARIO_REGISTRADOR CHAR(10), FOLIO_USUARIO_ACTUALIZADOR CHAR(10), FOLIO_FECHA_MAXIMA_RECEPCION DATE, PMT_NUMERO NUMERIC(3,0), OFICIO_REFERENCIA CHAR(30), LECHER NUMERIC(10,0), ESTATUS_FOLIO_CLAVE NUMERIC(5,0), FOLIO_OBSERVACION CHAR(200), FOLIO_FECHA_ENTREGA DATE, ESTATUS_FOLIO_CLAVE_2 NUMERIC(5,0), CONSTRAINT INTEG_248 PRIMARY KEY (FOLIO_NUMERO), CONSTRAINT FK_FOLIO_2 FOREIGN KEY (ESTATUS_FOLIO_CLAVE_2) REFERENCES FOL_ESTATUS(ESTATUS_FOLIO_CLAVE), CONSTRAINT INTEG_281 FOREIGN KEY (OFICIO_REFERENCIA) REFERENCES FOL_OFICIO_RECEPCION(OFICIO_REFERENCIA), CONSTRAINT INTEG_282 FOREIGN KEY (LECHER) REFERENCES LECHERIA(LECHER), CONSTRAINT INTEG_283 FOREIGN KEY (OFICIO_REFERENCIA) REFERENCES FOL_OFICIO_RECEPCION(OFICIO_REFERENCIA), CONSTRAINT INTEG_284 FOREIGN KEY (PMT_NUMERO) REFERENCES PROMOTOR(PMT_NUMERO), CONSTRAINT INTEG_285 FOREIGN KEY (LECHER) REFERENCES LECHERIA(LECHER), CONSTRAINT INTEG_286 FOREIGN KEY (OFICIO_REFERENCIA) REFERENCES FOL_OFICIO_RECEPCION(OFICIO_REFERENCIA), CONSTRAINT INTEG_287 FOREIGN KEY (LECHER) REFERENCES LECHERIA(LECHER));
CREATE INDEX FK_FOLIO_2 ON FOLIO (ESTATUS_FOLIO_CLAVE_2);
CREATE INDEX RDB$FOREIGN45 ON FOLIO (OFICIO_REFERENCIA);
CREATE INDEX RDB$FOREIGN46 ON FOLIO (LECHER);
CREATE INDEX RDB$FOREIGN47 ON FOLIO (OFICIO_REFERENCIA);
CREATE INDEX RDB$FOREIGN48 ON FOLIO (PMT_NUMERO);
CREATE INDEX RDB$FOREIGN49 ON FOLIO (LECHER);
CREATE INDEX RDB$FOREIGN50 ON FOLIO (OFICIO_REFERENCIA);
CREATE INDEX RDB$FOREIGN51 ON FOLIO (LECHER);
CREATE UNIQUE INDEX RDB$PRIMARY12 ON FOLIO (FOLIO_NUMERO);


-- FR_PROYECTADO definition

-- Drop table

-- DROP TABLE FR_PROYECTADO;

CREATE TABLE FR_PROYECTADO ( MES NUMERIC(2,0), ANIO NUMERIC(4,0), LECHER NUMERIC(10,0), DIAS_HABILES NUMERIC(2,0), PROM_VTAS_MES_ANTERIOR NUMERIC(5,2), BENEFICIARIOS_MES_ANTERIOR NUMERIC(5,0), LTS_PROGRAMADOS_MENSUALES NUMERIC(5,0), FR_PROYECTADO FLOAT, LTS_A_DISMINUIR NUMERIC(5,0), NUEVA_DOT_PROG_MENSUAL NUMERIC(5,0), FR_NUEVO FLOAT, CONSTRAINT FK_FR_PROYECTADO_1 FOREIGN KEY (LECHER) REFERENCES LECHERIA(LECHER));
CREATE INDEX FK_FR_PROYECTADO_1 ON FR_PROYECTADO (LECHER);


-- GUIA_VENTA_DIARIA definition

-- Drop table

-- DROP TABLE GUIA_VENTA_DIARIA;

CREATE TABLE GUIA_VENTA_DIARIA ( LECHER NUMERIC(10,0) NOT NULL, CVE_PRODUCTO VARCHAR(11) NOT NULL, FECHA_VENTA DATE NOT NULL, DOTACION_PROGRAMADA NUMERIC(5,0), FECHA_DISTRIBUCION DATE NOT NULL, ROTOS NUMERIC(5,0), FALTANTES NUMERIC(5,0), SOBRANTES NUMERIC(5,0), TRASPASOS NUMERIC(5,0), DEGUSTACION NUMERIC(5,0), DEVOLUCION_PLANTA NUMERIC(5,0), COSTO_LITRO NUMERIC(8,2), OBSERVACIONES BLOB SUB_TYPE TEXT, CAPTURADO VARCHAR(1), OBSERVACIONES_TRANSPORTISTA BLOB SUB_TYPE TEXT, MES_PERIODO_CIERRE NUMERIC(2,0), FECHA_REGISTRO_GUIA DATE, FECHA_REGISTRO_VENTA DATE, FECHA_ACTUALIZACION DATE, ANIO_PERIODO_CIERRE NUMERIC(4,0), CLAVE_RUTA NUMERIC(4,0), OBSERVACIONES_DISTRIBUCION BLOB SUB_TYPE TEXT, REGISTRO_PROCESADO_SAFCO NUMERIC(1,0), OBSERVACION_COMENTARIO VARCHAR(200), USUARIO_ACTUALIZADOR VARCHAR(15), USUARIO_REGISTRADOR VARCHAR(15), COMENTARIO_DAS30 BLOB SUB_TYPE TEXT, HORA_ENTREGA TIMESTAMP, ROTOS_RECOGIDOS NUMERIC(5,0), CANASTILLAS_RECOGIDAS NUMERIC(5,0), ARCHIVO_DAS30_IMPRESO VARCHAR(180), FOLIO_IMPRESO NUMERIC(10,0), CLAVE_PLANTA NUMERIC(5,0), CLAVE_RUTA_REPARTIDOR NUMERIC(5,0), CLAVE_CIA NUMERIC(5,0), SECUENCIA_DISTRIBUCION NUMERIC(2,0), RESPONSABLE_DEVOLUCION NUMERIC(1,0), HORA_ENTREGA_TXT VARCHAR(5), CONTINGENCIA VARCHAR(1), CONSTRAINT INTEG_250 PRIMARY KEY (LECHER,CVE_PRODUCTO,FECHA_VENTA), CONSTRAINT FK_GUIA_VENTA_DIARIA_1 FOREIGN KEY (CLAVE_CIA,LECHER,CLAVE_RUTA) REFERENCES RUTA_LECHERIA(CLAVE_CIA,LECHER,CLAVE_RUTA), CONSTRAINT INTEG_289 FOREIGN KEY (CVE_PRODUCTO) REFERENCES PRODUCTO(CVE_PRODUCTO), CONSTRAINT INTEG_290 FOREIGN KEY (CVE_PRODUCTO) REFERENCES PRODUCTO(CVE_PRODUCTO), CONSTRAINT INTEG_291 FOREIGN KEY (CVE_PRODUCTO) REFERENCES PRODUCTO(CVE_PRODUCTO));
CREATE INDEX FK_GUIA_VENTA_DIARIA_1 ON GUIA_VENTA_DIARIA (CLAVE_CIA,LECHER,CLAVE_RUTA);
CREATE INDEX GUIA_VENTA_DIARIA_IDX1 ON GUIA_VENTA_DIARIA (FOLIO_IMPRESO);
CREATE INDEX RDB$FOREIGN53 ON GUIA_VENTA_DIARIA (CVE_PRODUCTO);
CREATE INDEX RDB$FOREIGN54 ON GUIA_VENTA_DIARIA (CVE_PRODUCTO);
CREATE INDEX RDB$FOREIGN55 ON GUIA_VENTA_DIARIA (CVE_PRODUCTO);
CREATE UNIQUE INDEX RDB$PRIMARY14 ON GUIA_VENTA_DIARIA (LECHER,CVE_PRODUCTO,FECHA_VENTA);